import type { AssetClass } from "./cotMarkets";

export type Bias = "BULLISH" | "BEARISH" | "NEUTRAL";
export type Direction = "LONG" | "SHORT" | "NEUTRAL";

export type MarketSnapshot = {
  dealer_long: number;
  dealer_short: number;
  dealer_net: number;
  dealer_bias: Bias;
  commercial_long: number | null;
  commercial_short: number | null;
  commercial_net: number | null;
  commercial_bias: Bias | null;
  blended_long: number;
  blended_short: number;
  blended_net: number;
  blended_bias: Bias;
  dealer_delta_long?: number | null;
  dealer_delta_short?: number | null;
  dealer_delta_net?: number | null;
  commercial_delta_long?: number | null;
  commercial_delta_short?: number | null;
  commercial_delta_net?: number | null;
  open_interest?: number | null;
  oi_delta?: number | null;
  dealer_pct_of_oi?: number | null;
  commercial_pct_of_oi?: number | null;
  conc_gross_4_long?: number | null;
  conc_gross_4_short?: number | null;
  conc_gross_8_long?: number | null;
  conc_gross_8_short?: number | null;
  dealer_spread?: number | null;
  dealer_spread_delta?: number | null;
  dealer_directional_ratio?: number | null;
  dealer_delta_persistence?: number | null;
  commercial_delta_persistence?: number | null;
  dealer_pct_oi_long?: number | null;
  dealer_pct_oi_short?: number | null;
  dealer_traders_long?: number | null;
  dealer_traders_short?: number | null;
  asset_mgr_long?: number | null;
  asset_mgr_short?: number | null;
  asset_mgr_spread?: number | null;
  asset_mgr_net?: number | null;
  asset_mgr_delta_long?: number | null;
  asset_mgr_delta_short?: number | null;
  asset_mgr_delta_net?: number | null;
  asset_mgr_pct_oi_long?: number | null;
  asset_mgr_pct_oi_short?: number | null;
  asset_mgr_traders_long?: number | null;
  asset_mgr_traders_short?: number | null;
  lev_money_long?: number | null;
  lev_money_short?: number | null;
  lev_money_spread?: number | null;
  lev_money_net?: number | null;
  lev_money_delta_long?: number | null;
  lev_money_delta_short?: number | null;
  lev_money_delta_net?: number | null;
  lev_money_pct_oi_long?: number | null;
  lev_money_pct_oi_short?: number | null;
  lev_money_traders_long?: number | null;
  lev_money_traders_short?: number | null;
  other_rept_long?: number | null;
  other_rept_short?: number | null;
  other_rept_spread?: number | null;
  other_rept_net?: number | null;
  other_rept_delta_long?: number | null;
  other_rept_delta_short?: number | null;
  other_rept_delta_net?: number | null;
  nonrept_long?: number | null;
  nonrept_short?: number | null;
  nonrept_net?: number | null;
  nonrept_delta_long?: number | null;
  nonrept_delta_short?: number | null;
  nonrept_delta_net?: number | null;
  noncomm_long?: number | null;
  noncomm_short?: number | null;
  noncomm_spread?: number | null;
  noncomm_net?: number | null;
  noncomm_delta_long?: number | null;
  noncomm_delta_short?: number | null;
  noncomm_delta_spread?: number | null;
  noncomm_delta_net?: number | null;
  noncomm_pct_oi_long?: number | null;
  noncomm_pct_oi_short?: number | null;
  noncomm_traders_long?: number | null;
  noncomm_traders_short?: number | null;
  noncomm_traders_spread?: number | null;
  commercial_traders_long?: number | null;
  commercial_traders_short?: number | null;
  commercial_pct_oi_long?: number | null;
  commercial_pct_oi_short?: number | null;
  conc_net_4_long?: number | null;
  conc_net_4_short?: number | null;
  conc_net_8_long?: number | null;
  conc_net_8_short?: number | null;
};

export type PairSnapshot = {
  direction: Direction;
  base_bias: Bias;
  quote_bias: Bias;
};

export type CotSnapshot = {
  report_date: string;
  last_refresh_utc: string;
  asset_class: AssetClass;
  variant: string;
  currencies: Record<string, MarketSnapshot>;
  pairs: Record<string, PairSnapshot>;
};

export type CotSnapshotResponse = CotSnapshot & {
  trading_allowed: boolean;
  reason: string;
};
