/*-----------------------------------------------
  Property of Freedom_EXE  (c) 2026
-----------------------------------------------*/
/**
 * File: scheduledCronRegister.ts
 *
 * Description:
 * Phase 0 scheduled cron register. This keeps deployment schedules tied to
 * an explicit current architecture reason before durable run ledgers exist.
 */
/*-----------------------------------------------
  Manifested by Freedom_EXE
-----------------------------------------------*/

import type { ScheduledCronRegisterEntry } from "@/lib/appTruth/types";

export const APP_TRUTH_SCHEDULED_CRON_REGISTER: ScheduledCronRegisterEntry[] = [
  {
    id: "cot-refresh",
    label: "COT source refresh",
    path: "/api/cron/cot-refresh",
    schedules: ["0 * * * *", "*/10 19-23 * * 5", "*/10 19-23 * * 1"],
    status: "scheduled",
    owner: "data",
    sourceClass: "source_collection",
    currentRole: "Refreshes dealer, commercial, and sentiment source snapshots for active app data.",
    whyNeeded: "Data, Performance, source freeze evidence, and weekly canon all depend on current COT-style source rows before closed weeks are trusted.",
    risk: "Release/delay burst schedules can hide freshness gaps until SchedulerRunLedger exists.",
    nextGate: "Keep scheduled until Data DomainManifest and SchedulerRunLedger expose provider freshness and release-window receipts.",
  },
  {
    id: "prices-refresh",
    label: "Market price snapshot refresh",
    path: "/api/cron/prices-refresh",
    schedules: ["5 * * * *"],
    status: "scheduled",
    owner: "data",
    sourceClass: "source_collection",
    currentRole: "Refreshes current market snapshots used by Data and live dashboard context.",
    whyNeeded: "The app still shows live/current price context while closed weekly truth stays isolated.",
    risk: "Live snapshots can be mistaken for closed-week canon without lifecycle labels.",
    nextGate: "Keep until Data separates closed-week canon from live overlay in a domain manifest.",
  },
  {
    id: "sentiment-refresh",
    label: "Sentiment refresh",
    path: "/api/cron/sentiment-refresh",
    schedules: ["10 * * * *"],
    status: "scheduled",
    owner: "data",
    sourceClass: "source_collection",
    currentRole: "Refreshes Myfxbook-style sentiment aggregates for Data and signal context.",
    whyNeeded: "Sentiment remains an active input surface and must stay fresh for current-week overlay decisions.",
    risk: "Provider staleness is currently route-freshness based, not a durable app-truth receipt.",
    nextGate: "Keep until sentiment source freshness is represented in Data DomainManifest and run receipts.",
  },
  {
    id: "source-freeze",
    label: "Friday source freeze ledger",
    path: "/api/cron/source-freeze",
    schedules: ["15 21 * * 5", "15 22 * * 5"],
    status: "scheduled",
    owner: "data",
    sourceClass: "source_materialization",
    currentRole: "Builds the next display week's frozen dealer/commercial/sentiment/strength source ledger after Friday 5pm New York.",
    whyNeeded: "Data and current-week strategy overlays need a persisted frozen source ledger before the week becomes closed baseline history.",
    risk: "UTC cron has no DST awareness, so the route is scheduled twice and skips safely before the Friday cutoff.",
    nextGate: "Keep as the canonical source-freeze producer until a richer lifecycle scheduler replaces Vercel cron.",
  },
  {
    id: "news-refresh",
    label: "News and calendar refresh",
    path: "/api/cron/news-refresh",
    schedules: ["*/15 * * * *"],
    status: "scheduled",
    owner: "news",
    sourceClass: "source_collection",
    currentRole: "Refreshes news and economic calendar snapshots for the News/Dashboard surfaces.",
    whyNeeded: "News is a current operational context surface and should not depend on manual refresh.",
    risk: "High-frequency refresh has no durable provider receipt yet.",
    nextGate: "Keep until News has a domain manifest or the route is explicitly removed from the app.",
  },
  {
    id: "performance-refresh",
    label: "Legacy performance snapshot refresh",
    path: "/api/cron/performance-refresh",
    schedules: ["20 * * * *"],
    status: "scheduled",
    owner: "performance",
    sourceClass: "strategy_materialization",
    currentRole: "Refreshes performance_snapshots still consumed by Accounts, comparison, and transitional performance utilities.",
    whyNeeded: "Selected Performance truth no longer depends on this path, but active secondary surfaces still read these snapshots.",
    risk: "Can look like selected Performance truth if not labeled as transitional.",
    nextGate: "Delete or downgrade after Accounts/comparison surfaces move to explicit selected ledgers or are retired.",
  },
  {
    id: "strategy-artifacts",
    label: "Strategy artifact finalizer",
    path: "/api/cron/strategy-artifacts",
    schedules: ["40 * * * *"],
    status: "scheduled",
    owner: "performance",
    sourceClass: "strategy_materialization",
    currentRole: "Ensures visible strategy week shards exist for selected Performance runtime views.",
    whyNeeded: "Performance uses week shards for active selected strategy readiness before formal materialization ledgers exist.",
    risk: "Shard readiness is cron-observed instead of receipt-backed.",
    nextGate: "Keep until Performance materialization writes durable run receipts and selected ledger ids.",
  },
  {
    id: "active-baseline-certification",
    label: "Active baseline certification",
    path: "/api/cron/active-baseline-certification",
    schedules: ["55 * * * *"],
    status: "scheduled",
    owner: "status",
    sourceClass: "baseline_certification",
    currentRole: "Audits source-freeze, canonical/execution weekly returns, and strategy shards, then writes active-baseline receipts consumed by route gates.",
    whyNeeded: "Materialized rows alone are not route truth; Data and Performance gates need baseline receipts after weekly rollover.",
    risk: "If materializers lag, this route records a degraded certification until the missing rows appear.",
    nextGate: "Keep until app truth lifecycle promotion owns dependency ordering and certification as one scheduler workflow.",
  },
  {
    id: "market-snapshots",
    label: "Crypto market structure snapshots",
    path: "/api/cron/market-snapshots",
    schedules: ["0 * * * *"],
    status: "scheduled",
    owner: "automation",
    sourceClass: "source_collection",
    currentRole: "Collects funding, open interest, liquidation, and heatmap market structure snapshots.",
    whyNeeded: "This is the crypto/custom-strategy data lane Freedom explicitly wants preserved for future strategy buildout.",
    risk: "Collection can grow without a retention/materialization contract.",
    nextGate: "Keep; add retention and strategy-source receipts when crypto strategy research becomes active.",
  },
  {
    id: "currency-strength",
    label: "Currency strength refresh",
    path: "/api/cron/currency-strength",
    schedules: ["2 * * * *"],
    status: "scheduled",
    owner: "data",
    sourceClass: "source_collection",
    currentRole: "Computes FX currency strength snapshots for Data and flagship context.",
    whyNeeded: "Strength is an active app signal layer and future strategy input.",
    risk: "Strength snapshots are not yet attached to a domain manifest.",
    nextGate: "Keep until strength signals are versioned under Data/Strategy source truth.",
  },
  {
    id: "asset-strength",
    label: "Asset strength refresh",
    path: "/api/cron/asset-strength",
    schedules: ["3 * * * *"],
    status: "scheduled",
    owner: "data",
    sourceClass: "source_collection",
    currentRole: "Computes non-FX asset strength snapshots across crypto, commodities, and indices.",
    whyNeeded: "This supports the current matrix/flagship context and future custom strategies.",
    risk: "Strength snapshots are collected without materialized source receipts.",
    nextGate: "Keep until asset-strength source truth is represented in a Data/Strategy manifest.",
  },
  {
    id: "bitget-bot",
    label: "Bitget bot tick",
    path: "/api/cron/bitget-bot",
    schedules: ["* * * * *"],
    status: "scheduled",
    owner: "automation",
    sourceClass: "runtime_automation",
    currentRole: "Ticks the Bitget bot engine; returns IDLE when BITGET_BOT_ENABLED is false.",
    whyNeeded: "The automation lane remains active/future-facing and the route is feature-flagged safe when disabled.",
    risk: "Minute cadence needs explicit bot state and dry-run/live visibility.",
    nextGate: "Keep while Automation remains a planned surface; require bot run receipts before live trading approval.",
  },
  {
    id: "adr-trade-scan",
    label: "ADR trade scanner",
    path: "/api/cron/adr-trade-scan",
    schedules: ["25 * * * *"],
    status: "scheduled",
    owner: "performance",
    sourceClass: "strategy_materialization",
    currentRole: "Scans current-week ADR trades into strategy_backtest_trades for ADR/flagship flows.",
    whyNeeded: "ADR trade rows are actively consumed by weekly hold, flagship ADR endpoints, and strategy analysis.",
    risk: "Scanner output is not yet published as a selected trade-row ledger.",
    nextGate: "Keep until ADR rows are materialized under selected Strategy/Performance ledger identity.",
  },
  {
    id: "canonical-refresh",
    label: "Canonical price and weekly return refresh",
    path: "/api/cron/canonical-refresh?includeHourly=1",
    schedules: ["30 * * * *"],
    status: "scheduled",
    owner: "data",
    sourceClass: "price_materialization",
    currentRole: "Refreshes daily/hourly canonical bars and closed weekly return rows for current and previous weeks.",
    whyNeeded: "Closed-week canon, execution weekly returns, and crypto price data need provider-backed materialization.",
    risk: "It writes important data without SchedulerRunLedger coverage.",
    nextGate: "Keep until price materialization emits durable run receipts and closed/current week lifecycle states.",
  },
  {
    id: "menthorq-overlay-import",
    label: "MenthorQ CSV overlay import",
    path: "/api/cron/menthorq-overlay-import",
    schedules: [],
    status: "manual_only",
    owner: "automation",
    sourceClass: "manual_import",
    currentRole: "Authorized manual import of locally browser-captured MenthorQ CSV rows into overlay snapshots.",
    whyNeeded: "The runtime can read MenthorQ overlay snapshots, but the source CSV is account/browser captured and not produced by Vercel.",
    risk: "A scheduled deployment import would repeatedly process stale or missing local CSV data.",
    nextGate: "Schedule only after MenthorQ has an automated API/capture source plus run receipts.",
  },
  {
    id: "adr-trade-backfill",
    label: "ADR historical backfill",
    path: "/api/cron/adr-trade-backfill",
    schedules: [],
    status: "manual_only",
    owner: "performance",
    sourceClass: "one_shot_backfill",
    currentRole: "Authorized manual historical repair endpoint for ADR scanner output.",
    whyNeeded: "Backfill remains useful as a controlled maintenance hook, but it is not a recurring architecture job.",
    risk: "A yearly schedule can mutate old strategy rows without an explicit repair decision.",
    nextGate: "Run manually only when an ADR scanner repair/backfill is approved and documented.",
  },
];
