/*-----------------------------------------------
  Property of Freedom_EXE  (c) 2026
-----------------------------------------------*/
/**
 * File: state.ts
 *
 * Description:
 * Perpetual session state for Proteus. Reads and writes PROTEUS_STATE
 * to the database (poseidon_kv table) so state survives container
 * restarts, deploys, and infrastructure changes.
 *
 * Inspired by Will's Jarvis SESSION_STATE.md pattern.
 */
/*-----------------------------------------------
  Manifested by Freedom_EXE
-----------------------------------------------*/

import { kvGet, kvSet } from "@/lib/poseidon/state-db";
import { withStateLock } from "@/lib/poseidon/state-mutex";

const KV_KEY = "session_state";
export const STATE_SOFT_LIMIT_CHARS = 40_000;
const AUTO_TURN_MAX_CHARS = 1_200;

let cachedState: string | null = null;

/**
 * Load the current session state from the database.
 * Returns the markdown content, or empty string if none exists.
 */
export async function loadSessionState(): Promise<string> {
  if (cachedState !== null) return cachedState;
  try {
    const raw = await kvGet(KV_KEY);
    cachedState = raw;
    if (raw.length > 0) {
      console.log(`[poseidon.state] Loaded session state from DB (${raw.length} chars)`);
    } else {
      console.log("[poseidon.state] No existing session state in DB — fresh start");
    }
    return cachedState;
  } catch (error) {
    console.error("[poseidon.state] Failed to load state from DB:", error);
    cachedState = "";
    return cachedState;
  }
}

/**
 * Read the current state (for tools).
 */
export async function getSessionState(): Promise<string> {
  return await loadSessionState();
}

function stripStateHeader(content: string): string {
  return content.replace(/^# Proteus Session State\s*\n+(?:> Last updated:.*\n+)?/i, "").trim();
}

function formatStateDocument(content: string): string {
  const now = new Date().toISOString();
  const header = `# Proteus Session State\n\n> Last updated: ${now}\n\n`;
  const body = stripStateHeader(content);
  return `${header}${body}`;
}

function compactForState(text: string): string {
  return text.replace(/\s+/g, " ").trim();
}

export async function writeStateRaw(content: string): Promise<string> {
  const full = formatStateDocument(content);

  await kvSet(KV_KEY, full);
  cachedState = full;
  console.log(`[poseidon.state] Updated session state in DB (${full.length} chars)`);
  if (full.length > STATE_SOFT_LIMIT_CHARS) {
    console.warn(
      `[poseidon.state] State exceeds soft limit (${full.length} chars) - curation recommended`,
    );
  }
  return `Session state updated (${full.length} chars)`;
}

/**
 * Write new session state to DB. Called by Proteus via the
 * update_session_state tool when something meaningful happens.
 */
export async function updateSessionState(content: string): Promise<string> {
  return await withStateLock(async () => await writeStateRaw(content));
}

export async function getStateSize(): Promise<number> {
  const state = await loadSessionState();
  return state.length;
}

export async function appendConversationTurnToState(
  userMessage: string,
  assistantMessage: string,
): Promise<void> {
  await withStateLock(async () => {
    const current = await loadSessionState();
    const user = compactForState(userMessage).slice(0, AUTO_TURN_MAX_CHARS) || "(empty)";
    const assistant = compactForState(assistantMessage).slice(0, AUTO_TURN_MAX_CHARS) || "(empty)";

    const base = current && current.trim().length > 0
      ? current.trim()
      : [
        "## Active Context",
        "Autogenerated continuity log from live conversations.",
      ].join("\n\n");

    const entry = [
      `### ${new Date().toISOString()} - Conversation Turn`,
      `- User: ${user}`,
      `- Proteus: ${assistant}`,
    ].join("\n");

    await writeStateRaw(`${base}\n\n${entry}`);
  });
}

/**
 * Get a recovery summary for the startup message.
 * Returns null if there's no meaningful state to recover.
 */
export async function getRecoverySummary(): Promise<string | null> {
  const state = await loadSessionState();
  if (!state || state.length < 20) return null;

  const match = state.match(/Last updated:\s*(.+)/);
  const lastUpdated = match?.[1]?.trim() ?? "unknown";

  return `Proteus online. Recovered state from ${lastUpdated}.\n\nLast known context:\n${state.slice(0, 500)}`;
}
