/*-----------------------------------------------
  Property of Freedom_EXE  (c) 2026
-----------------------------------------------*/
/**
 * File: missed-turns.ts
 *
 * Description:
 * Fallback persistence for conversation turns when state writes fail.
 * Poseidon replays these turns during curation and then clears the queue.
 * Stored in the database (poseidon_kv table) for deploy-safe persistence.
 */
/*-----------------------------------------------
  Manifested by Freedom_EXE
-----------------------------------------------*/

import { kvGet, kvSet } from "@/lib/poseidon/state-db";
import { withStateLock } from "@/lib/poseidon/state-mutex";

export type MissedTurn = {
  timestamp: string;
  user_message: string;
  assistant_message: string;
  error: string;
};

const KV_KEY = "missed_turns";
const MAX_MISSED_TURNS = 200;

function asMissedTurn(raw: unknown): MissedTurn | null {
  if (!raw || typeof raw !== "object" || Array.isArray(raw)) return null;
  const row = raw as Record<string, unknown>;
  const timestamp = typeof row.timestamp === "string" ? row.timestamp : "";
  const userMessage = typeof row.user_message === "string" ? row.user_message : "";
  const assistantMessage = typeof row.assistant_message === "string" ? row.assistant_message : "";
  const error = typeof row.error === "string" ? row.error : "unknown";

  if (!timestamp || !userMessage || !assistantMessage) return null;
  return {
    timestamp,
    user_message: userMessage,
    assistant_message: assistantMessage,
    error,
  };
}

async function readRawMissedTurns(): Promise<MissedTurn[]> {
  try {
    const raw = await kvGet(KV_KEY);
    if (!raw) return [];
    const parsed = JSON.parse(raw);
    if (!Array.isArray(parsed)) return [];
    return parsed
      .map((entry) => asMissedTurn(entry))
      .filter((entry): entry is MissedTurn => entry !== null);
  } catch {
    return [];
  }
}

export async function readMissedTurns(): Promise<MissedTurn[]> {
  return await readRawMissedTurns();
}

export async function appendMissedTurn(
  userMessage: string,
  assistantMessage: string,
  error: string,
): Promise<void> {
  await withStateLock(async () => {
    const turns = await readRawMissedTurns();
    turns.push({
      timestamp: new Date().toISOString(),
      user_message: userMessage,
      assistant_message: assistantMessage,
      error,
    });

    const capped = turns.length > MAX_MISSED_TURNS
      ? turns.slice(-MAX_MISSED_TURNS)
      : turns;

    await kvSet(KV_KEY, JSON.stringify(capped));
  });
}

export async function clearMissedTurns(): Promise<void> {
  await withStateLock(async () => {
    await kvSet(KV_KEY, "[]");
  });
}

export function appendMissedTurnsToState(
  currentState: string,
  turns: MissedTurn[],
): string {
  if (turns.length === 0) return currentState;

  const base = currentState && currentState.trim().length > 0
    ? currentState.trim()
    : [
      "## Active Context",
      "Autogenerated continuity log from live conversations.",
    ].join("\n\n");

  const blocks = turns.map((turn) => [
    `### ${turn.timestamp} - Conversation Turn (Recovered)`,
    `- User: ${turn.user_message}`,
    `- Proteus: ${turn.assistant_message}`,
  ].join("\n"));

  return `${base}\n\n## Recovered Missed Turns\n\n${blocks.join("\n\n")}`;
}
