/*-----------------------------------------------
  Property of Freedom_EXE  (c) 2026
-----------------------------------------------*/
/**
 * File: backtest-strategy-gate-comparison.ts
 *
 * Description:
 * Compare baseline vs gate-overlay performance for Universal v1-v3
 * and Tiered v1-v3 over closed historical weeks.
 *
 * Gate overlay currently uses BTC/ETH gate decisions generated by:
 * - reports/bias-gate/btc-latest.json
 * - reports/bias-gate/eth-latest.json
 */
/*-----------------------------------------------
  Manifested by Freedom_EXE
-----------------------------------------------*/

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { DateTime } from "luxon";
import { loadEnvConfig } from "@next/env";

import { getPool, query } from "../src/lib/db";
import { listPerformanceWeeks, readPerformanceSnapshotsByWeek } from "../src/lib/performanceSnapshots";
import { getCanonicalWeekOpenUtc, normalizeWeekOpenUtc } from "../src/lib/weekAnchor";
import {
  PERFORMANCE_V1_MODELS,
  PERFORMANCE_V2_MODELS,
  PERFORMANCE_V3_MODELS,
  type PerformanceSystem,
} from "../src/lib/performance/modelConfig";
import type { PerformanceModel } from "../src/lib/performanceLab";
import { computeTieredForWeeksAllSystems } from "../src/lib/performance/tiered";
import { computeMaxDrawdownFromPercentReturns } from "../src/lib/performance/drawdown";
import { findLotMapEntry, type LotMapRow } from "../src/lib/accounts/mt5ViewHelpers";
import { readSnapshotHistory } from "../src/lib/cotStore";
import { PAIRS_BY_ASSET_CLASS } from "../src/lib/cotPairs";
import type { CotSnapshot } from "../src/lib/cotTypes";

type GateDecision = "PASS" | "REDUCE" | "SKIP" | "NO_DATA";
type StrategyId = "universal_v1" | "universal_v2" | "universal_v3" | "tiered_v1" | "tiered_v2" | "tiered_v3";
type AssetClassId = "fx" | "indices" | "crypto" | "commodities";
type GammaMode = "off" | "additive" | "only";
type GammaNeutralPolicy = "pass" | "skip" | "no_data";
type GammaCondition = "POSITIVE" | "NEGATIVE" | "NEUTRAL" | "UNKNOWN";

type CliConfig = {
  weeksRequested: number;
  weeks: number;
  outPath: string;
  sweep: boolean;
  sweepSkipValues: number[];
  sweepReduceValues: number[];
  reduceAsSkip: boolean;
  gammaMode: GammaMode;
  gammaNeutralPolicy: GammaNeutralPolicy;
  gammaWeekOpenCsv: string;
  gammaPairMapCsv: string;
};

type GateSignalRow = {
  weekStartUtc: string | null;
  weekStartLegacy: string | null;
  weekStartAny: string | null;
  gateDecision: GateDecision;
  gateReasons: string[];
};

type SnapshotTradeReturn = {
  pair: string;
  percent: number;
};

type ModelTradeReturn = SnapshotTradeReturn & {
  direction: TradeDirection | null;
};

type AssetBucketState = {
  baselineReturn: number;
  gatedReturn: number;
  baselineTrades: number;
  baselineWins: number;
  gatedTrades: number;
  gatedWins: number;
  baselineMarginUsd: number;
  gatedMarginUsd: number;
  skippedTrades: number;
  reducedTrades: number;
};

type WeekAssetBreakdown = {
  baselineReturn: number;
  gatedReturn: number;
  baselineTrades: number;
  gatedTrades: number;
  baselineMarginUsd: number;
  gatedMarginUsd: number;
  skippedTrades: number;
  reducedTrades: number;
};

type WeeklyBreakdown = {
  weekOpenUtc: string;
  baselineReturn: number;
  gatedReturn: number;
  baselineOpenTrades: number;
  gatedOpenTrades: number;
  baselineMarginUsd: number;
  gatedMarginUsd: number;
  skippedTrades: number;
  reducedTrades: number;
  perAsset: Record<AssetClassId, WeekAssetBreakdown>;
};

type SizingContext = {
  lotMapRows: LotMapRow[];
  accountScale: number;
  accountSizeUsd: number;
  baselineEquity: number;
  accountId: string;
  source: string;
};

type StrategyMetrics = {
  totalReturn: number;
  weeks: number;
  winRatePct: number;
  avgWeeklyPct: number;
  maxDrawdownPct: number;
  trades: number;
  tradeWinRatePct: number;
};

type StrategyComparison = {
  strategy: StrategyId;
  baseline: StrategyMetrics;
  gated: StrategyMetrics;
  delta: {
    totalReturnPct: number;
    winRatePct: number;
    avgWeeklyPct: number;
    maxDrawdownPct: number;
    trades: number;
    tradeWinRatePct: number;
  };
  gateActivity: {
    skippedTrades: number;
    reducedTrades: number;
    passedOrNoDataTrades: number;
  };
  capacity: {
    peakOpenTradesBaseline: number;
    peakOpenTradesGated: number;
    deltaPeakOpenTrades: number;
    avgOpenTradesBaseline: number;
    avgOpenTradesGated: number;
    deltaAvgOpenTrades: number;
    peakMarginBaselineUsd: number;
    peakMarginGatedUsd: number;
    freedPeakMarginUsd: number;
    avgMarginBaselineUsd: number;
    avgMarginGatedUsd: number;
    freedAvgMarginUsd: number;
    affectedWeeks: number;
    avgPotentialScaleOnAffectedWeeks: number;
    maxPotentialScaleOnAffectedWeeks: number;
  };
  perAsset: Record<
    AssetClassId,
    {
      baselineReturn: number;
      gatedReturn: number;
      deltaReturn: number;
      baselineTrades: number;
      gatedTrades: number;
      deltaTrades: number;
      baselineWinRatePct: number;
      gatedWinRatePct: number;
      baselineMarginUsd: number;
      gatedMarginUsd: number;
      deltaMarginUsd: number;
      skippedTrades: number;
      reducedTrades: number;
    }
  >;
  gateDiagnostics: {
    sourceCounts: Record<string, number>;
    decisionCounts: Record<GateDecision, number>;
    decisionByAsset: Record<AssetClassId, Record<GateDecision, number>>;
    reasonCounts: Record<string, number>;
    reasonByAsset: Record<AssetClassId, Record<string, number>>;
    reasonByPair: Record<string, Record<string, number>>;
    byModel: Record<string, Record<GateDecision, number>>;
  };
  weekly: WeeklyBreakdown[];
};

type GateEvaluation = {
  gatedPercent: number;
  decision: GateDecision;
  reasons: string[];
  source: "CRYPTO_LIQUIDATION" | "COT_PERCENTILE" | "GAMMA_WEEK_OPEN" | "NONE";
};

type GateDiagnosticsState = {
  sourceCounts: Record<string, number>;
  decisionCounts: Record<GateDecision, number>;
  decisionByAsset: Record<AssetClassId, Record<GateDecision, number>>;
  reasonCounts: Record<string, number>;
  reasonByAsset: Record<AssetClassId, Record<string, number>>;
  reasonByPair: Record<string, Record<string, number>>;
  byModel: Record<string, Record<GateDecision, number>>;
};

type StrategyAggregateState = {
  weeklyBaseline: number[];
  weeklyGated: number[];
  weeklyBreakdown: WeeklyBreakdown[];
  tradesBaseline: number;
  winsBaseline: number;
  tradesGated: number;
  winsGated: number;
  skippedTrades: number;
  reducedTrades: number;
  passedOrNoDataTrades: number;
  perAsset: Record<AssetClassId, AssetBucketState>;
  gateDiagnostics: GateDiagnosticsState;
};

type GateMap = Map<string, Map<string, { decision: GateDecision; reasons: string[] }>>;
type TradeDirection = "LONG" | "SHORT";

type CotWeekSnapshot = {
  weekOpenCanonical: string;
  weekOpenMs: number;
  snapshot: CotSnapshot;
};

type CotAssetHistory = {
  assetClass: AssetClassId;
  weeks: CotWeekSnapshot[];
};

type CotPairMeta = {
  assetClass: AssetClassId;
  base: string;
  quote: string;
};

type CotGateContext = {
  byAssetClass: Map<AssetClassId, CotAssetHistory>;
  pairMeta: Map<string, CotPairMeta>;
  minHistoryWeeks: number;
  skipPercentile: number;
  reducePercentile: number;
};

type GammaSnapshotEntry = {
  dateIso: string;
  dateMs: number;
  condition: GammaCondition;
};

type GammaPairMapEntry = {
  pair: string;
  baseSymbol: string | null;
  quoteSymbol: string | null;
  enabled: boolean;
};

type GammaGateContext = {
  mode: GammaMode;
  neutralPolicy: GammaNeutralPolicy;
  bySymbol: Map<string, GammaSnapshotEntry[]>;
  pairMap: Map<string, GammaPairMapEntry>;
  maxAgeDays: number;
  sourceFiles: {
    snapshotsCsv: string;
    pairMapCsv: string;
  };
};

type TieredWeekSystemRow = NonNullable<Awaited<ReturnType<typeof computeTieredForWeeksAllSystems>>["v1"][number]>;

const GATED_PAIRS = new Map<string, string>([
  ["BTCUSD", "BTC"],
  ["ETHUSD", "ETH"],
]);
const ASSET_CLASSES: AssetClassId[] = ["fx", "indices", "crypto", "commodities"];
const TARGET_ACCOUNT_SIZE_USD = Number(process.env.PERFORMANCE_TIERED_ACCOUNT_SIZE_USD ?? "100000");
const RESEARCH_MAX_WEEKS = 8;
const DEFAULT_GAMMA_WEEK_OPEN_CSV = "app/reports/bias-gate/menthorq-gamma-daily.csv";
const DEFAULT_GAMMA_PAIR_MAP_CSV = "app/reports/bias-gate/menthorq-gamma-symbol-map-template.csv";

const COT_PAIR_ALIASES = new Map<string, string>([
  ["US500", "SPXUSD"],
  ["SP500", "SPXUSD"],
  ["US100", "NDXUSD"],
  ["NAS100", "NDXUSD"],
  ["JP225", "NIKKEIUSD"],
  ["NIK225", "NIKKEIUSD"],
  ["GOLD", "XAUUSD"],
  ["SILVER", "XAGUSD"],
  ["USOIL", "WTIUSD"],
  ["UKOIL", "WTIUSD"],
]);

const COT_MARKET_ALIASES = new Map<string, string>([
  ["NAS100", "NDX"],
  ["US100", "NDX"],
  ["SP500", "SPX"],
  ["US500", "SPX"],
  ["JP225", "NIKKEI"],
  ["NIK225", "NIKKEI"],
  ["GOLD", "XAU"],
  ["SILVER", "XAG"],
  ["USOIL", "WTI"],
  ["UKOIL", "WTI"],
]);

function parseArgs(): CliConfig {
  const byKey = new Map<string, string>();
  for (const raw of process.argv.slice(2)) {
    if (!raw.startsWith("--")) continue;
    const [key, ...rest] = raw.slice(2).split("=");
    byKey.set(key.trim(), rest.join("="));
  }

  const weeksRaw = Number(byKey.get("weeks"));
  const requestedWeeks = Number.isFinite(weeksRaw) ? Math.max(1, Math.floor(weeksRaw)) : RESEARCH_MAX_WEEKS;
  const weeks = Math.min(requestedWeeks, RESEARCH_MAX_WEEKS);
  const outPath =
    byKey.get("out")?.trim() || "app/reports/bias-gate/strategy-comparison-latest.json";
  const sweepRaw = String(byKey.get("sweep") ?? "").trim().toLowerCase();
  const sweep = sweepRaw === "1" || sweepRaw === "true" || sweepRaw === "yes" || sweepRaw === "on";
  const reduceAsSkipRaw = String(byKey.get("reduce-as-skip") ?? "").trim().toLowerCase();
  const reduceAsSkip =
    reduceAsSkipRaw === "1" ||
    reduceAsSkipRaw === "true" ||
    reduceAsSkipRaw === "yes" ||
    reduceAsSkipRaw === "on";
  const sweepSkipValues = parseNumberList(byKey.get("sweep-skip"), [90, 92.5, 95]);
  const sweepReduceValues = parseNumberList(byKey.get("sweep-reduce"), [75, 80, 85]);
  const gammaModeRaw = String(byKey.get("gamma-mode") ?? process.env.GAMMA_MODE ?? "off").trim().toLowerCase();
  const gammaMode: GammaMode = gammaModeRaw === "only" ? "only" : gammaModeRaw === "additive" ? "additive" : "off";
  const gammaNeutralRaw = String(byKey.get("gamma-neutral-policy") ?? process.env.GAMMA_NEUTRAL_POLICY ?? "pass")
    .trim()
    .toLowerCase();
  const gammaNeutralPolicy: GammaNeutralPolicy =
    gammaNeutralRaw === "skip" ? "skip" : gammaNeutralRaw === "no_data" ? "no_data" : "pass";
  const gammaWeekOpenCsv = byKey.get("gamma-week-open-csv")?.trim() || process.env.GAMMA_WEEK_OPEN_CSV || DEFAULT_GAMMA_WEEK_OPEN_CSV;
  const gammaPairMapCsv = byKey.get("gamma-pair-map-csv")?.trim() || process.env.GAMMA_PAIR_MAP_CSV || DEFAULT_GAMMA_PAIR_MAP_CSV;

  return {
    weeksRequested: requestedWeeks,
    weeks,
    outPath,
    sweep,
    sweepSkipValues,
    sweepReduceValues,
    reduceAsSkip,
    gammaMode,
    gammaNeutralPolicy,
    gammaWeekOpenCsv,
    gammaPairMapCsv,
  };
}

function round(value: number, decimals = 4): number {
  const scale = 10 ** decimals;
  return Math.round(value * scale) / scale;
}

function toAssetClassId(value: unknown): AssetClassId | null {
  const raw = String(value ?? "").trim().toLowerCase();
  if (raw === "fx" || raw === "indices" || raw === "crypto" || raw === "commodities") {
    return raw;
  }
  return null;
}

function parseNumberList(raw: string | undefined, fallback: number[]): number[] {
  if (!raw || raw.trim().length === 0) return fallback;
  const parsed = raw
    .split(",")
    .map((part) => Number(part.trim()))
    .filter((value) => Number.isFinite(value));
  return parsed.length > 0 ? parsed : fallback;
}

function parseCsvLine(line: string): string[] {
  const out: string[] = [];
  let current = "";
  let inQuotes = false;
  for (let i = 0; i < line.length; i += 1) {
    const ch = line[i];
    if (ch === '"') {
      if (inQuotes && line[i + 1] === '"') {
        current += '"';
        i += 1;
      } else {
        inQuotes = !inQuotes;
      }
      continue;
    }
    if (ch === "," && !inQuotes) {
      out.push(current.trim());
      current = "";
      continue;
    }
    current += ch;
  }
  out.push(current.trim());
  return out;
}

function parseCsvObjects(filePath: string): Array<Record<string, string>> {
  const resolved = path.resolve(process.cwd(), filePath);
  if (!existsSync(resolved)) return [];
  const raw = readFileSync(resolved, "utf8");
  const lines = raw.split(/\r?\n/).filter((line) => line.trim().length > 0);
  if (lines.length < 2) return [];
  const headers = parseCsvLine(lines[0]).map((header) => header.trim().toLowerCase());
  const out: Array<Record<string, string>> = [];
  for (const line of lines.slice(1)) {
    const values = parseCsvLine(line);
    const row: Record<string, string> = {};
    headers.forEach((header, index) => {
      row[header] = values[index] ?? "";
    });
    out.push(row);
  }
  return out;
}

function emptyAssetBucket(): AssetBucketState {
  return {
    baselineReturn: 0,
    gatedReturn: 0,
    baselineTrades: 0,
    baselineWins: 0,
    gatedTrades: 0,
    gatedWins: 0,
    baselineMarginUsd: 0,
    gatedMarginUsd: 0,
    skippedTrades: 0,
    reducedTrades: 0,
  };
}

function makeAssetBucketRecord(): Record<AssetClassId, AssetBucketState> {
  return {
    fx: emptyAssetBucket(),
    indices: emptyAssetBucket(),
    crypto: emptyAssetBucket(),
    commodities: emptyAssetBucket(),
  };
}

function emptyWeekAssetBreakdown(): WeekAssetBreakdown {
  return {
    baselineReturn: 0,
    gatedReturn: 0,
    baselineTrades: 0,
    gatedTrades: 0,
    baselineMarginUsd: 0,
    gatedMarginUsd: 0,
    skippedTrades: 0,
    reducedTrades: 0,
  };
}

function makeWeekAssetBreakdownRecord(): Record<AssetClassId, WeekAssetBreakdown> {
  return {
    fx: emptyWeekAssetBreakdown(),
    indices: emptyWeekAssetBreakdown(),
    crypto: emptyWeekAssetBreakdown(),
    commodities: emptyWeekAssetBreakdown(),
  };
}

function parseLotMapRows(value: unknown): LotMapRow[] {
  if (!value) return [];
  if (Array.isArray(value)) return value as LotMapRow[];
  if (typeof value === "string") {
    try {
      const parsed = JSON.parse(value);
      return Array.isArray(parsed) ? (parsed as LotMapRow[]) : [];
    } catch {
      return [];
    }
  }
  return [];
}

function weekOpenFromCotReportDate(reportDate: string): string | null {
  const report = DateTime.fromISO(reportDate, { zone: "utc" }).startOf("day");
  if (!report.isValid) return null;
  const weekOpen = report.startOf("week").plus({ weeks: 1 }).toUTC().toISO();
  return weekOpen ?? null;
}

function parseCotNet(value: unknown): number | null {
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : null;
}

function resolveCotMarketNet(
  snapshot: CotSnapshot,
  assetClass: AssetClassId,
  marketId: string,
): number | null {
  const resolvedMarketId = resolveCotMarketId(assetClass, marketId);
  if (!resolvedMarketId) return null;
  const market = snapshot.currencies[resolvedMarketId] as Record<string, unknown> | undefined;
  if (!market) return null;

  // Keep sign convention aligned with cotCompute.ts.
  if (assetClass === "commodities") {
    const commercialLong = parseCotNet(market.commercial_long);
    const commercialShort = parseCotNet(market.commercial_short);
    if (commercialLong !== null && commercialShort !== null) {
      return commercialLong - commercialShort;
    }
  }

  const dealerLong = parseCotNet(market.dealer_long);
  const dealerShort = parseCotNet(market.dealer_short);
  if (dealerLong === null || dealerShort === null) return null;
  return dealerShort - dealerLong;
}

function directionalPercentile(values: number[], current: number, direction: TradeDirection): number {
  const n = values.length;
  if (n === 0) return 0;
  if (direction === "LONG") {
    const rank = values.filter((value) => value <= current).length;
    return (rank / n) * 100;
  }
  const rank = values.filter((value) => value >= current).length;
  return (rank / n) * 100;
}

function parseJsonFile<T>(filePath: string): T | null {
  if (!existsSync(filePath)) return null;
  try {
    return JSON.parse(readFileSync(filePath, "utf8")) as T;
  } catch {
    return null;
  }
}

function normalizePair(value: unknown): string {
  return String(value ?? "").trim().toUpperCase();
}

function normalizeCotPairAlias(pair: string): { canonicalPair: string; aliasApplied: boolean } {
  const normalized = normalizePair(pair);
  const aliased = COT_PAIR_ALIASES.get(normalized);
  if (!aliased) {
    return { canonicalPair: normalized, aliasApplied: false };
  }
  return { canonicalPair: aliased, aliasApplied: aliased !== normalized };
}

function resolveCotMarketId(assetClass: AssetClassId, marketId: string): string | null {
  const raw = String(marketId ?? "").trim().toUpperCase();
  if (!raw) return null;
  if ((assetClass === "indices" || assetClass === "commodities") && raw === "USD") {
    // COT index/commodity snapshots are base-market only in this dataset.
    return null;
  }
  return COT_MARKET_ALIASES.get(raw) ?? raw;
}

function toFinite(value: unknown): number | null {
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : null;
}

function emptyGateDecisionCounts(): Record<GateDecision, number> {
  return {
    PASS: 0,
    REDUCE: 0,
    SKIP: 0,
    NO_DATA: 0,
  };
}

function incrementCount(counter: Record<string, number>, key: string) {
  counter[key] = (counter[key] ?? 0) + 1;
}

function makeGateDiagnosticsState(): GateDiagnosticsState {
  return {
    sourceCounts: {},
    decisionCounts: emptyGateDecisionCounts(),
    decisionByAsset: {
      fx: emptyGateDecisionCounts(),
      indices: emptyGateDecisionCounts(),
      crypto: emptyGateDecisionCounts(),
      commodities: emptyGateDecisionCounts(),
    },
    reasonCounts: {},
    reasonByAsset: {
      fx: {},
      indices: {},
      crypto: {},
      commodities: {},
    },
    reasonByPair: {},
    byModel: {},
  };
}

function recordGateDiagnostics(options: {
  state: StrategyAggregateState;
  assetClass: AssetClassId | null;
  pair: string;
  result: GateEvaluation;
  model?: string | null;
}) {
  incrementCount(options.state.gateDiagnostics.sourceCounts, options.result.source);
  options.state.gateDiagnostics.decisionCounts[options.result.decision] += 1;

  const normalizedPair = normalizePair(options.pair);
  if (options.assetClass) {
    options.state.gateDiagnostics.decisionByAsset[options.assetClass][options.result.decision] += 1;
  }

  const reasons = options.result.reasons.length > 0 ? options.result.reasons : ["UNSPECIFIED"];
  for (const reason of reasons) {
    incrementCount(options.state.gateDiagnostics.reasonCounts, reason);
    if (options.assetClass) {
      incrementCount(options.state.gateDiagnostics.reasonByAsset[options.assetClass], reason);
    }
    if (!options.state.gateDiagnostics.reasonByPair[normalizedPair]) {
      options.state.gateDiagnostics.reasonByPair[normalizedPair] = {};
    }
    incrementCount(options.state.gateDiagnostics.reasonByPair[normalizedPair], reason);
  }

  const modelKey = String(options.model ?? "").trim().toLowerCase();
  if (modelKey) {
    if (!options.state.gateDiagnostics.byModel[modelKey]) {
      options.state.gateDiagnostics.byModel[modelKey] = emptyGateDecisionCounts();
    }
    options.state.gateDiagnostics.byModel[modelKey][options.result.decision] += 1;
  }
}

function normalizeTradeDirection(value: unknown): TradeDirection | null {
  const raw = String(value ?? "").trim().toUpperCase();
  if (raw === "LONG" || raw === "SHORT") return raw;
  return null;
}

function buildPairDirectionQueues(pairDetails: unknown): Map<string, TradeDirection[]> {
  const out = new Map<string, TradeDirection[]>();
  if (!Array.isArray(pairDetails)) return out;

  const pushDirection = (pairRaw: unknown, directionRaw: unknown) => {
    const pair = normalizePair(pairRaw);
    if (!pair) return;
    const direction = normalizeTradeDirection(directionRaw);
    if (!direction) return;
    const list = out.get(pair) ?? [];
    list.push(direction);
    out.set(pair, list);
  };

  for (const detailRaw of pairDetails) {
    if (!detailRaw || typeof detailRaw !== "object") continue;
    const detail = detailRaw as Record<string, unknown>;
    pushDirection(detail.pair, detail.direction);
    if (Array.isArray(detail.children)) {
      for (const childRaw of detail.children) {
        if (!childRaw || typeof childRaw !== "object") continue;
        const child = childRaw as Record<string, unknown>;
        pushDirection(child.pair, child.direction);
      }
    }
  }
  return out;
}

function attachTradeDirections(returns: SnapshotTradeReturn[], pairDetails: unknown): ModelTradeReturn[] {
  const queues = buildPairDirectionQueues(pairDetails);
  return returns.map((entry) => {
    const queue = queues.get(entry.pair) ?? [];
    const direction = queue.length > 0 ? (queue.shift() ?? null) : null;
    if (queue.length > 0) {
      queues.set(entry.pair, queue);
    } else {
      queues.delete(entry.pair);
    }
    return {
      pair: entry.pair,
      percent: entry.percent,
      direction,
    };
  });
}

function parseGammaCondition(value: string): GammaCondition {
  const raw = String(value ?? "").trim().toUpperCase();
  if (raw.startsWith("POS")) return "POSITIVE";
  if (raw.startsWith("NEG")) return "NEGATIVE";
  if (raw.startsWith("NEU")) return "NEUTRAL";
  return "UNKNOWN";
}

function gammaConditionToDirection(condition: GammaCondition): TradeDirection | null {
  if (condition === "POSITIVE") return "LONG";
  if (condition === "NEGATIVE") return "SHORT";
  return null;
}

function weekOpenDateIso(weekOpenUtc: string): string {
  const dt = DateTime.fromISO(weekOpenUtc, { zone: "utc" });
  if (!dt.isValid) return weekOpenUtc.slice(0, 10);
  return dt.toFormat("yyyy-LL-dd");
}

function resolveGammaSnapshotForDate(options: {
  symbol: string;
  targetDateIso: string;
  context: GammaGateContext;
}): { condition: GammaCondition; sourceDateIso: string } | null {
  const symbol = normalizePair(options.symbol);
  const series = options.context.bySymbol.get(symbol);
  if (!series || series.length === 0) return null;

  const target = DateTime.fromISO(options.targetDateIso, { zone: "utc" }).startOf("day");
  if (!target.isValid) return null;
  const targetMs = target.toMillis();
  let best: GammaSnapshotEntry | null = null;
  for (const row of series) {
    if (row.dateMs <= targetMs) {
      best = row;
    } else {
      break;
    }
  }
  if (!best) return null;
  const diffDays = Math.floor((targetMs - best.dateMs) / 86_400_000);
  if (diffDays > options.context.maxAgeDays) return null;
  return {
    condition: best.condition,
    sourceDateIso: best.dateIso,
  };
}

function buildGammaGateContext(config: CliConfig): GammaGateContext | null {
  if (config.gammaMode === "off") return null;
  const snapshotRows = parseCsvObjects(config.gammaWeekOpenCsv);
  const pairMapRows = parseCsvObjects(config.gammaPairMapCsv);
  if (snapshotRows.length === 0 || pairMapRows.length === 0) {
    return null;
  }

  const bySymbol = new Map<string, GammaSnapshotEntry[]>();
  for (const row of snapshotRows) {
    const dateIso = String(row.date ?? "").trim();
    const symbol = normalizePair(row.page_symbol || row.symbol_input || row.symbol || "");
    const condition = parseGammaCondition(row.gamma_condition || row.gammacondition || "");
    const dateMs = DateTime.fromISO(dateIso, { zone: "utc" }).startOf("day").toMillis();
    if (!symbol || !dateIso || !Number.isFinite(dateMs)) continue;
    const list = bySymbol.get(symbol) ?? [];
    list.push({
      dateIso,
      dateMs,
      condition,
    });
    bySymbol.set(symbol, list);
  }
  for (const list of bySymbol.values()) {
    list.sort((a, b) => a.dateMs - b.dateMs);
  }

  const pairMap = new Map<string, GammaPairMapEntry>();
  for (const row of pairMapRows) {
    const pair = normalizePair(row.pair || "");
    const baseSymbolRaw = normalizePair(row.base_gamma_symbol || row.base_symbol || row.base || "");
    const quoteSymbolRaw = normalizePair(row.quote_gamma_symbol || row.quote_symbol || row.quote || "");
    const baseSymbol = baseSymbolRaw.length > 0 ? baseSymbolRaw : null;
    const quoteSymbol = quoteSymbolRaw.length > 0 ? quoteSymbolRaw : null;
    const enabledRaw = String(row.enabled ?? "1").trim().toLowerCase();
    const enabled = !(enabledRaw === "0" || enabledRaw === "false" || enabledRaw === "no" || enabledRaw === "off");
    if (!pair || (!baseSymbol && !quoteSymbol)) continue;
    pairMap.set(pair, {
      pair,
      baseSymbol,
      quoteSymbol,
      enabled,
    });
  }

  return {
    mode: config.gammaMode,
    neutralPolicy: config.gammaNeutralPolicy,
    bySymbol,
    pairMap,
    maxAgeDays: 8,
    sourceFiles: {
      snapshotsCsv: config.gammaWeekOpenCsv,
      pairMapCsv: config.gammaPairMapCsv,
    },
  };
}

function evaluateGammaWeekOpenGate(options: {
  pair: string;
  direction: TradeDirection | null;
  weekOpenUtc: string;
  context: GammaGateContext;
}): { decision: GateDecision; reasons: string[] } {
  if (!options.direction) {
    return { decision: "NO_DATA", reasons: ["GAMMA_DIRECTION_MISSING"] };
  }
  const pair = normalizePair(options.pair);
  const map = options.context.pairMap.get(pair);
  if (!map || !map.enabled) {
    return { decision: "NO_DATA", reasons: ["GAMMA_PAIR_NOT_MAPPED"] };
  }
  if (!map.baseSymbol && !map.quoteSymbol) {
    return { decision: "NO_DATA", reasons: ["GAMMA_PAIR_EMPTY_MAPPING"] };
  }

  const targetDateIso = weekOpenDateIso(options.weekOpenUtc);
  const baseSnapshot = map.baseSymbol
    ? resolveGammaSnapshotForDate({
        symbol: map.baseSymbol,
        targetDateIso,
        context: options.context,
      })
    : null;
  const quoteSnapshot = map.quoteSymbol
    ? resolveGammaSnapshotForDate({
        symbol: map.quoteSymbol,
        targetDateIso,
        context: options.context,
      })
    : null;

  if (!baseSnapshot && !quoteSnapshot) {
    return { decision: "NO_DATA", reasons: ["GAMMA_SYMBOL_DATA_MISSING"] };
  }

  const desiredBase = options.direction;
  const desiredQuote: TradeDirection = options.direction === "LONG" ? "SHORT" : "LONG";
  const reasons: string[] = [];
  let conflict = false;
  let alignmentHits = 0;
  let neutralHits = 0;

  if (baseSnapshot) {
    reasons.push(`GAMMA_BASE_DATE_${baseSnapshot.sourceDateIso}`);
    const dir = gammaConditionToDirection(baseSnapshot.condition);
    if (!dir) {
      neutralHits += 1;
    } else if (dir === desiredBase) {
      alignmentHits += 1;
    } else {
      conflict = true;
      reasons.push("GAMMA_BASE_CONFLICT");
    }
  }
  if (!map.baseSymbol) {
    reasons.push("GAMMA_BASE_UNMAPPED");
  } else if (!baseSnapshot) {
    reasons.push("GAMMA_BASE_MISSING");
  }

  if (quoteSnapshot) {
    reasons.push(`GAMMA_QUOTE_DATE_${quoteSnapshot.sourceDateIso}`);
    const dir = gammaConditionToDirection(quoteSnapshot.condition);
    if (!dir) {
      neutralHits += 1;
    } else if (dir === desiredQuote) {
      alignmentHits += 1;
    } else {
      conflict = true;
      reasons.push("GAMMA_QUOTE_CONFLICT");
    }
  }
  if (!map.quoteSymbol) {
    reasons.push("GAMMA_QUOTE_UNMAPPED");
  } else if (!quoteSnapshot) {
    reasons.push("GAMMA_QUOTE_MISSING");
  }

  if (conflict) {
    reasons.push("GAMMA_WEEK_OPEN_SKIP_CONFLICT");
    return { decision: "SKIP", reasons };
  }

  if (alignmentHits > 0) {
    reasons.push("GAMMA_WEEK_OPEN_PASS_ALIGNED");
    return { decision: "PASS", reasons };
  }

  if (neutralHits > 0) {
    if (options.context.neutralPolicy === "skip") {
      reasons.push("GAMMA_WEEK_OPEN_SKIP_NEUTRAL");
      return { decision: "SKIP", reasons };
    }
    if (options.context.neutralPolicy === "no_data") {
      reasons.push("GAMMA_WEEK_OPEN_NO_DATA_NEUTRAL");
      return { decision: "NO_DATA", reasons };
    }
    reasons.push("GAMMA_WEEK_OPEN_PASS_NEUTRAL");
    return { decision: "PASS", reasons };
  }

  return { decision: "NO_DATA", reasons: ["GAMMA_WEEK_OPEN_NO_SIGNAL"] };
}

function toGateDecision(value: unknown): GateDecision {
  const raw = String(value ?? "").trim().toUpperCase();
  if (raw === "PASS" || raw === "REDUCE" || raw === "SKIP" || raw === "NO_DATA") return raw;
  return "NO_DATA";
}

function coerceGateSignalRows(raw: unknown): GateSignalRow[] {
  if (!Array.isArray(raw)) return [];
  return raw.map((item) => {
    const row = item && typeof item === "object" ? (item as Record<string, unknown>) : {};
    const weekStartUtc = typeof row.weekStartUtc === "string"
      ? row.weekStartUtc
      : typeof row.week_start_utc === "string"
        ? row.week_start_utc
        : null;
    const weekStartLegacy = typeof row.week_start === "string"
      ? row.week_start
      : typeof row.weekStart === "string"
        ? row.weekStart
        : null;
    const weekStartAny = weekStartUtc ?? weekStartLegacy;
    return {
      weekStartUtc,
      weekStartLegacy,
      weekStartAny,
      gateDecision: toGateDecision(row.gateDecision ?? row.gate_decision),
      gateReasons: (() => {
        const reasonsRaw = row.gateReasons ?? row.gate_reasons;
        return Array.isArray(reasonsRaw) ? reasonsRaw.map((v: unknown) => String(v)) : [];
      })(),
    };
  });
}

function buildGateMapForSymbol(symbol: string): Map<string, { decision: GateDecision; reasons: string[] }> {
  const reportsDir = path.resolve(process.cwd(), "app", "reports", "bias-gate");
  const localLatest = path.join(reportsDir, `${symbol.toLowerCase()}-latest.json`);
  const rootLatest = path.resolve(process.cwd(), "app", "reports", `backtest-${symbol.toLowerCase()}-bias-gate-latest.json`);
  const source =
    parseJsonFile<Record<string, unknown>>(localLatest) ??
    parseJsonFile<Record<string, unknown>>(rootLatest);
  const out = new Map<string, { decision: GateDecision; reasons: string[] }>();
  if (!source) return out;

  const rows = coerceGateSignalRows(source.signals);
  for (const row of rows) {
    const candidates = [
      row.weekStartUtc,
      row.weekStartLegacy,
      row.weekStartAny,
    ].filter((value): value is string => Boolean(value));
    for (const candidate of candidates) {
      let iso = candidate;
      if (!candidate.includes("T")) {
        iso = `${candidate}T00:00:00.000Z`;
      }
      const canonical = normalizeWeekOpenUtc(iso) ?? normalizeWeekOpenUtc(candidate) ?? candidate;
      out.set(canonical, {
        decision: row.gateDecision,
        reasons: row.gateReasons,
      });
    }
  }
  return out;
}

function buildGateMap(): GateMap {
  const out: GateMap = new Map();
  for (const [, symbol] of GATED_PAIRS.entries()) {
    out.set(symbol, buildGateMapForSymbol(symbol));
  }
  return out;
}

async function buildCotGateContext(): Promise<CotGateContext> {
  const byAssetClass = new Map<AssetClassId, CotAssetHistory>();
  const pairMeta = new Map<string, CotPairMeta>();

  (["fx", "indices", "commodities"] as AssetClassId[]).forEach((assetClass) => {
    for (const pairDef of PAIRS_BY_ASSET_CLASS[assetClass]) {
      const canonicalPair = normalizePair(pairDef.pair);
      const meta = {
        assetClass,
        base: pairDef.base,
        quote: pairDef.quote,
      } satisfies CotPairMeta;
      pairMeta.set(canonicalPair, meta);

      for (const [alias, target] of COT_PAIR_ALIASES.entries()) {
        if (normalizePair(target) === canonicalPair) {
          pairMeta.set(alias, meta);
        }
      }
    }
  });

  for (const assetClass of ["fx", "indices", "commodities"] as AssetClassId[]) {
    const history = await readSnapshotHistory(assetClass, 260);
    const weeks = history
      .map((snapshot) => {
        const weekOpen = weekOpenFromCotReportDate(snapshot.report_date);
        if (!weekOpen) return null;
        const canonical = normalizeWeekOpenUtc(weekOpen) ?? weekOpen;
        const millis = DateTime.fromISO(canonical, { zone: "utc" }).toMillis();
        if (!Number.isFinite(millis)) return null;
        return {
          weekOpenCanonical: canonical,
          weekOpenMs: millis,
          snapshot,
        } satisfies CotWeekSnapshot;
      })
      .filter((entry): entry is CotWeekSnapshot => entry !== null)
      .sort((a, b) => a.weekOpenMs - b.weekOpenMs);

    byAssetClass.set(assetClass, {
      assetClass,
      weeks,
    });
  }

  return {
    byAssetClass,
    pairMeta,
    minHistoryWeeks: 10,
    skipPercentile: 90,
    reducePercentile: 75,
  };
}

function evaluateCotPercentileGate(options: {
  pair: string;
  weekOpenUtc: string;
  direction: TradeDirection;
  assetClass: AssetClassId;
  context: CotGateContext;
}): { decision: GateDecision; reasons: string[] } {
  if (options.assetClass !== "fx" && options.assetClass !== "indices" && options.assetClass !== "commodities") {
    return { decision: "NO_DATA", reasons: ["COT_UNSUPPORTED_ASSET_CLASS"] };
  }

  const { canonicalPair, aliasApplied } = normalizeCotPairAlias(options.pair);
  const meta = options.context.pairMeta.get(canonicalPair);
  if (!meta) {
    return { decision: "NO_DATA", reasons: ["COT_PAIR_META_MISSING"] };
  }

  const assetHistory = options.context.byAssetClass.get(meta.assetClass);
  if (!assetHistory || assetHistory.weeks.length === 0) {
    return { decision: "NO_DATA", reasons: ["COT_HISTORY_MISSING"] };
  }

  const targetWeek = normalizeWeekOpenUtc(options.weekOpenUtc) ?? options.weekOpenUtc;
  const targetMs = DateTime.fromISO(targetWeek, { zone: "utc" }).toMillis();
  if (!Number.isFinite(targetMs)) {
    return { decision: "NO_DATA", reasons: ["COT_INVALID_WEEK"] };
  }

  let snapshotIndex = -1;
  for (let i = 0; i < assetHistory.weeks.length; i += 1) {
    if (assetHistory.weeks[i].weekOpenMs <= targetMs) {
      snapshotIndex = i;
    } else {
      break;
    }
  }
  if (snapshotIndex < 0) {
    return { decision: "NO_DATA", reasons: ["COT_NO_PRIOR_SNAPSHOT"] };
  }

  const depth = snapshotIndex + 1;
  if (depth < options.context.minHistoryWeeks) {
    return { decision: "NO_DATA", reasons: ["COT_INSUFFICIENT_HISTORY"] };
  }

  const baseTradeDirection: TradeDirection = options.direction === "LONG" ? "LONG" : "SHORT";
  const quoteTradeDirection: TradeDirection = options.direction === "LONG" ? "SHORT" : "LONG";
  const weeksSlice = assetHistory.weeks.slice(0, snapshotIndex + 1);

  const baseMarketId = resolveCotMarketId(meta.assetClass, meta.base);
  const quoteMarketId = resolveCotMarketId(meta.assetClass, meta.quote);
  if (!baseMarketId) {
    return { decision: "NO_DATA", reasons: ["COT_BASE_MARKET_UNRESOLVED"] };
  }

  const baseSeries = weeksSlice
    .map((row) => resolveCotMarketNet(row.snapshot, meta.assetClass, baseMarketId))
    .filter((value): value is number => value !== null);
  const quoteSeries = quoteMarketId
    ? weeksSlice
        .map((row) => resolveCotMarketNet(row.snapshot, meta.assetClass, quoteMarketId))
        .filter((value): value is number => value !== null)
    : [];

  if (baseSeries.length < options.context.minHistoryWeeks) {
    return { decision: "NO_DATA", reasons: ["COT_BASE_HISTORY_GAPS"] };
  }
  if (quoteMarketId && quoteSeries.length < options.context.minHistoryWeeks) {
    return { decision: "NO_DATA", reasons: ["COT_QUOTE_HISTORY_GAPS"] };
  }

  const baseCurrent = baseSeries[baseSeries.length - 1];
  const basePct = directionalPercentile(baseSeries, baseCurrent, baseTradeDirection);
  const quoteCurrent = quoteSeries.length > 0 ? quoteSeries[quoteSeries.length - 1] : null;
  const quotePct = quoteCurrent === null ? null : directionalPercentile(quoteSeries, quoteCurrent, quoteTradeDirection);

  const reasons: string[] = [];
  if (aliasApplied) reasons.push("COT_PAIR_ALIAS_APPLIED");
  if (!quoteMarketId) reasons.push("COT_SINGLE_MARKET_MODE_BASE_ONLY");

  if (basePct > options.context.skipPercentile || (quotePct !== null && quotePct > options.context.skipPercentile)) {
    if (basePct > options.context.skipPercentile) reasons.push("COT_SKIP_BASE_EXTREME");
    if (quotePct !== null && quotePct > options.context.skipPercentile) reasons.push("COT_SKIP_QUOTE_EXTREME");
    return { decision: "SKIP", reasons };
  }
  if (basePct > options.context.reducePercentile || (quotePct !== null && quotePct > options.context.reducePercentile)) {
    if (basePct > options.context.reducePercentile) reasons.push("COT_REDUCE_BASE_CROWDED");
    if (quotePct !== null && quotePct > options.context.reducePercentile) reasons.push("COT_REDUCE_QUOTE_CROWDED");
    return { decision: "REDUCE", reasons };
  }

  return { decision: "PASS", reasons: ["COT_PASS"] };
}

async function loadSizingContext(accountSizeUsd = TARGET_ACCOUNT_SIZE_USD): Promise<SizingContext | null> {
  const rows = await query<{
    account_id: string;
    baseline_equity: string | number | null;
    lot_map: LotMapRow[] | string | null;
  }>(
    `SELECT account_id, baseline_equity, lot_map
       FROM mt5_accounts
      ORDER BY
        CASE WHEN LOWER(COALESCE(broker, '')) LIKE '%eightcap%' THEN 0 ELSE 1 END,
        CASE WHEN UPPER(COALESCE(status, '')) = 'ACTIVE' THEN 0 ELSE 1 END,
        COALESCE(updated_at, last_sync_utc, NOW()) DESC`,
  );

  for (const row of rows) {
    const lotMapRows = parseLotMapRows(row.lot_map);
    if (lotMapRows.length === 0) continue;
    const baselineEquity = toFinite(row.baseline_equity) ?? accountSizeUsd;
    const accountScale = baselineEquity > 0 ? accountSizeUsd / baselineEquity : 1;
    return {
      lotMapRows,
      accountScale,
      accountSizeUsd,
      baselineEquity,
      accountId: row.account_id,
      source: "mt5_accounts.lot_map",
    };
  }
  return null;
}

function estimateTradeMarginUsd(pair: string, sizing: SizingContext | null): number {
  if (!sizing) return 0;
  const lot = findLotMapEntry(sizing.lotMapRows, pair);
  const base = toFinite(lot?.margin_required);
  if (base === null || base <= 0) return 0;
  return base * sizing.accountScale;
}

function gateMultiplier(decision: GateDecision, reduceAsSkip = false): number {
  if (decision === "SKIP") return 0;
  if (decision === "REDUCE") return reduceAsSkip ? 0 : 0.5;
  return 1;
}

function evaluatePairWithGate(options: {
  pair: string;
  percent: number;
  weekOpenUtc: string;
  direction: TradeDirection | null;
  assetClass: AssetClassId | null;
  gateMap: GateMap;
  cotContext: CotGateContext | null;
  gammaContext: GammaGateContext | null;
  reduceAsSkip: boolean;
}): GateEvaluation {
  const pair = normalizePair(options.pair);
  const symbol = GATED_PAIRS.get(pair);

  if (options.gammaContext && options.direction) {
    const gamma = evaluateGammaWeekOpenGate({
      pair,
      direction: options.direction,
      weekOpenUtc: options.weekOpenUtc,
      context: options.gammaContext,
    });
    const gammaDecision =
      options.reduceAsSkip && gamma.decision === "REDUCE" ? "SKIP" : gamma.decision;
    const gammaResult: GateEvaluation = {
      gatedPercent: options.percent * gateMultiplier(gammaDecision, options.reduceAsSkip),
      decision: gammaDecision,
      reasons: gamma.reasons,
      source: "GAMMA_WEEK_OPEN",
    };
    if (options.gammaContext.mode === "only") {
      return gammaResult;
    }
    if (gammaResult.decision === "SKIP") {
      return gammaResult;
    }
  }

  // Crypto liquidation gate (BTC/ETH) has priority.
  if (symbol) {
    const gate = options.gateMap.get(symbol)?.get(options.weekOpenUtc);
    const rawDecision = gate?.decision ?? "NO_DATA";
    const decision =
      options.reduceAsSkip && rawDecision === "REDUCE" ? "SKIP" : rawDecision;
    const reasons = gate?.reasons?.length ? [...gate.reasons] : [`CRYPTO_GATE_${rawDecision}`];
    if (options.reduceAsSkip && rawDecision === "REDUCE") {
      reasons.push("REDUCE_ESCALATED_TO_SKIP");
    }
    const multiplier = gateMultiplier(decision, options.reduceAsSkip);
    return {
      gatedPercent: options.percent * multiplier,
      decision,
      reasons,
      source: "CRYPTO_LIQUIDATION",
    };
  }

  // COT percentile gate for non-crypto (currently fx/indices/commodities).
  if (
    options.cotContext &&
    options.direction &&
    options.assetClass &&
    options.assetClass !== "crypto"
  ) {
    const cot = evaluateCotPercentileGate({
      pair,
      weekOpenUtc: options.weekOpenUtc,
      direction: options.direction,
      assetClass: options.assetClass,
      context: options.cotContext,
    });
    const decision =
      options.reduceAsSkip && cot.decision === "REDUCE" ? "SKIP" : cot.decision;
    const reasons = [...cot.reasons];
    if (options.reduceAsSkip && cot.decision === "REDUCE") {
      reasons.push("REDUCE_ESCALATED_TO_SKIP");
    }
    return {
      gatedPercent: options.percent * gateMultiplier(decision, options.reduceAsSkip),
      decision,
      reasons,
      source: "COT_PERCENTILE",
    };
  }

  const noDataReasons: string[] = [];
  if (!options.cotContext) noDataReasons.push("COT_CONTEXT_MISSING");
  if (!options.gammaContext && options.direction) noDataReasons.push("GAMMA_CONTEXT_MISSING");
  if (!options.direction) noDataReasons.push("COT_DIRECTION_MISSING");
  if (!options.assetClass) noDataReasons.push("ASSET_CLASS_MISSING");
  if (options.assetClass === "crypto") noDataReasons.push("CRYPTO_NON_PRIORITY_PAIR");
  if (noDataReasons.length === 0) noDataReasons.push("GATE_NOT_APPLICABLE");
  return {
    gatedPercent: options.percent,
    decision: "NO_DATA" as GateDecision,
    reasons: noDataReasons,
    source: "NONE",
  };
}

function computeMetricsFromState(state: StrategyAggregateState): { baseline: StrategyMetrics; gated: StrategyMetrics } {
  const baselineTotal = state.weeklyBaseline.reduce((sum, value) => sum + value, 0);
  const gatedTotal = state.weeklyGated.reduce((sum, value) => sum + value, 0);
  const baselineWeeks = state.weeklyBaseline.length;
  const gatedWeeks = state.weeklyGated.length;
  const baselineWeekWins = state.weeklyBaseline.filter((value) => value > 0).length;
  const gatedWeekWins = state.weeklyGated.filter((value) => value > 0).length;

  const baseline: StrategyMetrics = {
    totalReturn: round(baselineTotal),
    weeks: baselineWeeks,
    winRatePct: baselineWeeks > 0 ? round((baselineWeekWins / baselineWeeks) * 100, 2) : 0,
    avgWeeklyPct: baselineWeeks > 0 ? round(baselineTotal / baselineWeeks) : 0,
    maxDrawdownPct: round(computeMaxDrawdownFromPercentReturns(state.weeklyBaseline), 6),
    trades: state.tradesBaseline,
    tradeWinRatePct: state.tradesBaseline > 0 ? round((state.winsBaseline / state.tradesBaseline) * 100, 2) : 0,
  };
  const gated: StrategyMetrics = {
    totalReturn: round(gatedTotal),
    weeks: gatedWeeks,
    winRatePct: gatedWeeks > 0 ? round((gatedWeekWins / gatedWeeks) * 100, 2) : 0,
    avgWeeklyPct: gatedWeeks > 0 ? round(gatedTotal / gatedWeeks) : 0,
    maxDrawdownPct: round(computeMaxDrawdownFromPercentReturns(state.weeklyGated), 6),
    trades: state.tradesGated,
    tradeWinRatePct: state.tradesGated > 0 ? round((state.winsGated / state.tradesGated) * 100, 2) : 0,
  };
  return { baseline, gated };
}

function emptyState(): StrategyAggregateState {
  return {
    weeklyBaseline: [],
    weeklyGated: [],
    weeklyBreakdown: [],
    tradesBaseline: 0,
    winsBaseline: 0,
    tradesGated: 0,
    winsGated: 0,
    skippedTrades: 0,
    reducedTrades: 0,
    passedOrNoDataTrades: 0,
    perAsset: makeAssetBucketRecord(),
    gateDiagnostics: makeGateDiagnosticsState(),
  };
}

async function listClosedWeeks(limit: number): Promise<string[]> {
  const allWeeks = await listPerformanceWeeks(52);
  const currentWeekOpenUtc = getCanonicalWeekOpenUtc();
  const currentMs = DateTime.fromISO(currentWeekOpenUtc, { zone: "utc" }).toMillis();
  const closed = allWeeks.filter((week) => {
    const millis = DateTime.fromISO(week, { zone: "utc" }).toMillis();
    return Number.isFinite(millis) && millis < currentMs;
  });
  return closed
    .slice(0, limit)
    .sort(
      (a, b) =>
        DateTime.fromISO(a, { zone: "utc" }).toMillis() -
        DateTime.fromISO(b, { zone: "utc" }).toMillis(),
    );
}

async function computeUniversalStrategy(options: {
  weeks: string[];
  models: PerformanceModel[];
  gateMap: GateMap;
  cotContext: CotGateContext | null;
  gammaContext: GammaGateContext | null;
  sizing: SizingContext | null;
  reduceAsSkip: boolean;
}): Promise<StrategyAggregateState> {
  const state = emptyState();
  for (const weekOpenUtc of options.weeks) {
    const snapshots = await readPerformanceSnapshotsByWeek(weekOpenUtc);
    const byModel = new Map<PerformanceModel, Array<typeof snapshots[number]>>();
    for (const row of snapshots) {
      if (!options.models.includes(row.model)) continue;
      const list = byModel.get(row.model) ?? [];
      list.push(row);
      byModel.set(row.model, list);
    }

    const activeModels = options.models.filter((model) => (byModel.get(model)?.length ?? 0) > 0);
    if (activeModels.length === 0) {
      state.weeklyBaseline.push(0);
      state.weeklyGated.push(0);
      state.weeklyBreakdown.push({
        weekOpenUtc,
        baselineReturn: 0,
        gatedReturn: 0,
        baselineOpenTrades: 0,
        gatedOpenTrades: 0,
        baselineMarginUsd: 0,
        gatedMarginUsd: 0,
        skippedTrades: 0,
        reducedTrades: 0,
        perAsset: makeWeekAssetBreakdownRecord(),
      });
      continue;
    }

    let baselineWeekSum = 0;
    let gatedWeekSum = 0;
    let baselineWeekTrades = 0;
    let gatedWeekTrades = 0;
    let baselineWeekMargin = 0;
    let gatedWeekMargin = 0;
    let skippedWeekTrades = 0;
    let reducedWeekTrades = 0;
    const assetBaselineNumerator = new Map<AssetClassId, number>();
    const assetGatedNumerator = new Map<AssetClassId, number>();
    const weekAssetBreakdown = makeWeekAssetBreakdownRecord();
    for (const model of activeModels) {
      const rows = byModel.get(model) ?? [];
      let baselineModel = 0;
      let gatedModel = 0;
      for (const row of rows) {
        const assetClass = toAssetClassId(row.asset_class);
        baselineModel += row.percent;
        if (assetClass) {
          assetBaselineNumerator.set(assetClass, (assetBaselineNumerator.get(assetClass) ?? 0) + row.percent);
        }
        let rowAdjustment = 0;
        const returns: SnapshotTradeReturn[] = Array.isArray(row.returns)
          ? row.returns
              .map((entry) => ({
                pair: normalizePair((entry as Record<string, unknown>).pair),
                percent: toFinite((entry as Record<string, unknown>).percent),
              }))
              .filter((entry): entry is { pair: string; percent: number } => entry.percent !== null)
          : [];
        const modelTrades = attachTradeDirections(returns, row.pair_details);
        for (const entry of modelTrades) {
          const pair = entry.pair;
          const pct = entry.percent;
          const baselineMargin = estimateTradeMarginUsd(pair, options.sizing);

          state.tradesBaseline += 1;
          if (pct > 0) state.winsBaseline += 1;
          baselineWeekTrades += 1;
          baselineWeekMargin += baselineMargin;
          if (assetClass) {
            state.perAsset[assetClass].baselineTrades += 1;
            if (pct > 0) state.perAsset[assetClass].baselineWins += 1;
            state.perAsset[assetClass].baselineMarginUsd += baselineMargin;
            weekAssetBreakdown[assetClass].baselineTrades += 1;
            weekAssetBreakdown[assetClass].baselineMarginUsd += baselineMargin;
          }

          const evaluated = evaluatePairWithGate({
            pair,
            percent: pct,
            weekOpenUtc,
            direction: entry.direction,
            assetClass,
            gateMap: options.gateMap,
            cotContext: options.cotContext,
            gammaContext: options.gammaContext,
            reduceAsSkip: options.reduceAsSkip,
          });
          recordGateDiagnostics({
            state,
            assetClass,
            pair,
            result: evaluated,
            model,
          });
          if (evaluated.decision === "SKIP") {
            state.skippedTrades += 1;
            skippedWeekTrades += 1;
            if (assetClass) {
              state.perAsset[assetClass].skippedTrades += 1;
              weekAssetBreakdown[assetClass].skippedTrades += 1;
            }
          } else {
            state.tradesGated += 1;
            if (evaluated.gatedPercent > 0) state.winsGated += 1;
            gatedWeekTrades += 1;
            const gatedMargin = baselineMargin * gateMultiplier(evaluated.decision, options.reduceAsSkip);
            gatedWeekMargin += gatedMargin;
            if (assetClass) {
              state.perAsset[assetClass].gatedTrades += 1;
              if (evaluated.gatedPercent > 0) state.perAsset[assetClass].gatedWins += 1;
              state.perAsset[assetClass].gatedMarginUsd += gatedMargin;
              weekAssetBreakdown[assetClass].gatedTrades += 1;
              weekAssetBreakdown[assetClass].gatedMarginUsd += gatedMargin;
            }
            if (evaluated.decision === "REDUCE") {
              state.reducedTrades += 1;
              reducedWeekTrades += 1;
              if (assetClass) {
                state.perAsset[assetClass].reducedTrades += 1;
                weekAssetBreakdown[assetClass].reducedTrades += 1;
              }
            } else {
              state.passedOrNoDataTrades += 1;
            }
          }

          if (evaluated.gatedPercent !== pct) {
            rowAdjustment += evaluated.gatedPercent - pct;
          }
        }
        const gatedRowPercent = row.percent + rowAdjustment;
        gatedModel += gatedRowPercent;
        if (assetClass) {
          assetGatedNumerator.set(assetClass, (assetGatedNumerator.get(assetClass) ?? 0) + gatedRowPercent);
        }
      }
      baselineWeekSum += baselineModel;
      gatedWeekSum += gatedModel;
    }

    const baselineWeekReturn = baselineWeekSum / activeModels.length;
    const gatedWeekReturn = gatedWeekSum / activeModels.length;
    state.weeklyBaseline.push(baselineWeekReturn);
    state.weeklyGated.push(gatedWeekReturn);
    for (const assetClass of ASSET_CLASSES) {
      const baselineAssetReturn = (assetBaselineNumerator.get(assetClass) ?? 0) / activeModels.length;
      const gatedAssetReturn = (assetGatedNumerator.get(assetClass) ?? 0) / activeModels.length;
      state.perAsset[assetClass].baselineReturn += baselineAssetReturn;
      state.perAsset[assetClass].gatedReturn += gatedAssetReturn;
      weekAssetBreakdown[assetClass].baselineReturn = baselineAssetReturn;
      weekAssetBreakdown[assetClass].gatedReturn = gatedAssetReturn;
    }
    state.weeklyBreakdown.push({
      weekOpenUtc,
      baselineReturn: baselineWeekReturn,
      gatedReturn: gatedWeekReturn,
      baselineOpenTrades: baselineWeekTrades,
      gatedOpenTrades: gatedWeekTrades,
      baselineMarginUsd: baselineWeekMargin,
      gatedMarginUsd: gatedWeekMargin,
      skippedTrades: skippedWeekTrades,
      reducedTrades: reducedWeekTrades,
      perAsset: weekAssetBreakdown,
    });
  }
  return state;
}

function accumulateTieredTradesFromModel(options: {
  modelReturns: ModelTradeReturn[];
  modelName: string;
  assetClass: AssetClassId;
  weekOpenUtc: string;
  gateMap: GateMap;
  cotContext: CotGateContext | null;
  gammaContext: GammaGateContext | null;
  state: StrategyAggregateState;
  sizing: SizingContext | null;
  weekAssetBreakdown: Record<AssetClassId, WeekAssetBreakdown>;
  reduceAsSkip: boolean;
}) {
  for (const detail of options.modelReturns) {
    const pair = normalizePair(detail.pair);
    const pct = detail.percent;
    const baselineMargin = estimateTradeMarginUsd(pair, options.sizing);

    options.state.tradesBaseline += 1;
    if (pct > 0) options.state.winsBaseline += 1;
    options.state.perAsset[options.assetClass].baselineTrades += 1;
    if (pct > 0) options.state.perAsset[options.assetClass].baselineWins += 1;
    options.state.perAsset[options.assetClass].baselineMarginUsd += baselineMargin;
    options.weekAssetBreakdown[options.assetClass].baselineTrades += 1;
    options.weekAssetBreakdown[options.assetClass].baselineMarginUsd += baselineMargin;

    const evaluated = evaluatePairWithGate({
      pair,
      percent: pct,
      weekOpenUtc: options.weekOpenUtc,
      direction: detail.direction,
      assetClass: options.assetClass,
      gateMap: options.gateMap,
      cotContext: options.cotContext,
      gammaContext: options.gammaContext,
      reduceAsSkip: options.reduceAsSkip,
    });
    recordGateDiagnostics({
      state: options.state,
      assetClass: options.assetClass,
      pair,
      result: evaluated,
      model: options.modelName,
    });
    if (evaluated.decision === "SKIP") {
      options.state.skippedTrades += 1;
      options.state.perAsset[options.assetClass].skippedTrades += 1;
      options.weekAssetBreakdown[options.assetClass].skippedTrades += 1;
    } else {
      options.state.tradesGated += 1;
      if (evaluated.gatedPercent > 0) options.state.winsGated += 1;
      options.state.perAsset[options.assetClass].gatedTrades += 1;
      if (evaluated.gatedPercent > 0) options.state.perAsset[options.assetClass].gatedWins += 1;
      const gatedMargin = baselineMargin * gateMultiplier(evaluated.decision, options.reduceAsSkip);
      options.state.perAsset[options.assetClass].gatedMarginUsd += gatedMargin;
      options.weekAssetBreakdown[options.assetClass].gatedTrades += 1;
      options.weekAssetBreakdown[options.assetClass].gatedMarginUsd += gatedMargin;
      if (evaluated.decision === "REDUCE") {
        options.state.reducedTrades += 1;
        options.state.perAsset[options.assetClass].reducedTrades += 1;
        options.weekAssetBreakdown[options.assetClass].reducedTrades += 1;
      } else {
        options.state.passedOrNoDataTrades += 1;
      }
    }
  }
}

function computeTieredStrategy(options: {
  weeklyRows: TieredWeekSystemRow[];
  gateMap: GateMap;
  cotContext: CotGateContext | null;
  gammaContext: GammaGateContext | null;
  sizing: SizingContext | null;
  reduceAsSkip: boolean;
}): StrategyAggregateState {
  const state = emptyState();
  const sorted = [...options.weeklyRows].sort(
    (a, b) =>
      DateTime.fromISO(a.week_open_utc, { zone: "utc" }).toMillis() -
      DateTime.fromISO(b.week_open_utc, { zone: "utc" }).toMillis(),
  );
  for (const weekRow of sorted) {
    const baselineWeek = weekRow.summary.return_percent;
    let gatedWeek = 0;
    let baselineWeekTrades = 0;
    let gatedWeekTrades = 0;
    let baselineWeekMargin = 0;
    let gatedWeekMargin = 0;
    let skippedWeekTrades = 0;
    let reducedWeekTrades = 0;
    const weekAssetBreakdown = makeWeekAssetBreakdownRecord();

    for (const assetClass of ASSET_CLASSES) {
      const models = weekRow.perAsset[assetClass] ?? [];
      let baselineAsset = 0;
      let gatedAsset = 0;
      for (const model of models) {
        let adjustment = 0;
        const returns: SnapshotTradeReturn[] = (model.returns ?? [])
          .map((entry) => ({
            pair: normalizePair(entry.pair),
            percent: toFinite(entry.percent),
          }))
          .filter((entry): entry is SnapshotTradeReturn => entry.percent !== null);
        const modelTrades = attachTradeDirections(returns, model.pair_details);

        for (const detail of modelTrades) {
          const baselineMargin = estimateTradeMarginUsd(detail.pair, options.sizing);
          baselineWeekTrades += 1;
          baselineWeekMargin += baselineMargin;

          const decision = evaluatePairWithGate({
            pair: detail.pair,
            percent: detail.percent,
            weekOpenUtc: weekRow.week_open_utc,
            direction: detail.direction,
            assetClass,
            gateMap: options.gateMap,
            cotContext: options.cotContext,
            gammaContext: options.gammaContext,
            reduceAsSkip: options.reduceAsSkip,
          });
          if (decision.decision === "SKIP") {
            skippedWeekTrades += 1;
          } else {
            gatedWeekTrades += 1;
            const gatedMargin = baselineMargin * gateMultiplier(decision.decision, options.reduceAsSkip);
            gatedWeekMargin += gatedMargin;
            if (decision.decision === "REDUCE") {
              reducedWeekTrades += 1;
            }
          }
          if (decision.gatedPercent !== detail.percent) {
            adjustment += decision.gatedPercent - detail.percent;
          }
        }

        baselineAsset += model.percent;
        gatedAsset += model.percent + adjustment;
        accumulateTieredTradesFromModel({
          modelReturns: modelTrades,
          modelName: model.model,
          assetClass,
          weekOpenUtc: weekRow.week_open_utc,
          gateMap: options.gateMap,
          cotContext: options.cotContext,
          gammaContext: options.gammaContext,
          state,
          sizing: options.sizing,
          weekAssetBreakdown,
          reduceAsSkip: options.reduceAsSkip,
        });
      }
      weekAssetBreakdown[assetClass].baselineReturn = baselineAsset;
      weekAssetBreakdown[assetClass].gatedReturn = gatedAsset;
      state.perAsset[assetClass].baselineReturn += baselineAsset;
      state.perAsset[assetClass].gatedReturn += gatedAsset;
      gatedWeek += gatedAsset;
    }

    state.weeklyBaseline.push(baselineWeek);
    state.weeklyGated.push(gatedWeek);
    state.weeklyBreakdown.push({
      weekOpenUtc: weekRow.week_open_utc,
      baselineReturn: baselineWeek,
      gatedReturn: gatedWeek,
      baselineOpenTrades: baselineWeekTrades,
      gatedOpenTrades: gatedWeekTrades,
      baselineMarginUsd: baselineWeekMargin,
      gatedMarginUsd: gatedWeekMargin,
      skippedTrades: skippedWeekTrades,
      reducedTrades: reducedWeekTrades,
      perAsset: weekAssetBreakdown,
    });
  }
  return state;
}

function compareStrategy(strategy: StrategyId, state: StrategyAggregateState): StrategyComparison {
  const metrics = computeMetricsFromState(state);
  const baselineOpenSeries = state.weeklyBreakdown.map((row) => row.baselineOpenTrades);
  const gatedOpenSeries = state.weeklyBreakdown.map((row) => row.gatedOpenTrades);
  const baselineMarginSeries = state.weeklyBreakdown.map((row) => row.baselineMarginUsd);
  const gatedMarginSeries = state.weeklyBreakdown.map((row) => row.gatedMarginUsd);
  const affectedWeeks = state.weeklyBreakdown.filter((row) => row.skippedTrades > 0 || row.reducedTrades > 0);
  const potentialScales = affectedWeeks
    .map((row) => (row.gatedMarginUsd > 0 ? row.baselineMarginUsd / row.gatedMarginUsd : 1))
    .filter((value) => Number.isFinite(value) && value > 0);
  const avg = (values: number[]) => (values.length > 0 ? values.reduce((s, v) => s + v, 0) / values.length : 0);
  const peak = (values: number[]) => (values.length > 0 ? Math.max(...values) : 0);

  const perAsset = {
    fx: state.perAsset.fx,
    indices: state.perAsset.indices,
    crypto: state.perAsset.crypto,
    commodities: state.perAsset.commodities,
  };

  return {
    strategy,
    baseline: metrics.baseline,
    gated: metrics.gated,
    delta: {
      totalReturnPct: round(metrics.gated.totalReturn - metrics.baseline.totalReturn),
      winRatePct: round(metrics.gated.winRatePct - metrics.baseline.winRatePct, 2),
      avgWeeklyPct: round(metrics.gated.avgWeeklyPct - metrics.baseline.avgWeeklyPct),
      maxDrawdownPct: round(metrics.gated.maxDrawdownPct - metrics.baseline.maxDrawdownPct, 6),
      trades: metrics.gated.trades - metrics.baseline.trades,
      tradeWinRatePct: round(metrics.gated.tradeWinRatePct - metrics.baseline.tradeWinRatePct, 2),
    },
    gateActivity: {
      skippedTrades: state.skippedTrades,
      reducedTrades: state.reducedTrades,
      passedOrNoDataTrades: state.passedOrNoDataTrades,
    },
    capacity: {
      peakOpenTradesBaseline: peak(baselineOpenSeries),
      peakOpenTradesGated: peak(gatedOpenSeries),
      deltaPeakOpenTrades: peak(gatedOpenSeries) - peak(baselineOpenSeries),
      avgOpenTradesBaseline: round(avg(baselineOpenSeries), 2),
      avgOpenTradesGated: round(avg(gatedOpenSeries), 2),
      deltaAvgOpenTrades: round(avg(gatedOpenSeries) - avg(baselineOpenSeries), 2),
      peakMarginBaselineUsd: round(peak(baselineMarginSeries), 2),
      peakMarginGatedUsd: round(peak(gatedMarginSeries), 2),
      freedPeakMarginUsd: round(peak(baselineMarginSeries) - peak(gatedMarginSeries), 2),
      avgMarginBaselineUsd: round(avg(baselineMarginSeries), 2),
      avgMarginGatedUsd: round(avg(gatedMarginSeries), 2),
      freedAvgMarginUsd: round(avg(baselineMarginSeries) - avg(gatedMarginSeries), 2),
      affectedWeeks: affectedWeeks.length,
      avgPotentialScaleOnAffectedWeeks: round(avg(potentialScales), 6),
      maxPotentialScaleOnAffectedWeeks: round(peak(potentialScales), 6),
    },
    perAsset: {
      fx: {
        baselineReturn: round(perAsset.fx.baselineReturn),
        gatedReturn: round(perAsset.fx.gatedReturn),
        deltaReturn: round(perAsset.fx.gatedReturn - perAsset.fx.baselineReturn),
        baselineTrades: perAsset.fx.baselineTrades,
        gatedTrades: perAsset.fx.gatedTrades,
        deltaTrades: perAsset.fx.gatedTrades - perAsset.fx.baselineTrades,
        baselineWinRatePct: perAsset.fx.baselineTrades > 0 ? round((perAsset.fx.baselineWins / perAsset.fx.baselineTrades) * 100, 2) : 0,
        gatedWinRatePct: perAsset.fx.gatedTrades > 0 ? round((perAsset.fx.gatedWins / perAsset.fx.gatedTrades) * 100, 2) : 0,
        baselineMarginUsd: round(perAsset.fx.baselineMarginUsd, 2),
        gatedMarginUsd: round(perAsset.fx.gatedMarginUsd, 2),
        deltaMarginUsd: round(perAsset.fx.gatedMarginUsd - perAsset.fx.baselineMarginUsd, 2),
        skippedTrades: perAsset.fx.skippedTrades,
        reducedTrades: perAsset.fx.reducedTrades,
      },
      indices: {
        baselineReturn: round(perAsset.indices.baselineReturn),
        gatedReturn: round(perAsset.indices.gatedReturn),
        deltaReturn: round(perAsset.indices.gatedReturn - perAsset.indices.baselineReturn),
        baselineTrades: perAsset.indices.baselineTrades,
        gatedTrades: perAsset.indices.gatedTrades,
        deltaTrades: perAsset.indices.gatedTrades - perAsset.indices.baselineTrades,
        baselineWinRatePct: perAsset.indices.baselineTrades > 0 ? round((perAsset.indices.baselineWins / perAsset.indices.baselineTrades) * 100, 2) : 0,
        gatedWinRatePct: perAsset.indices.gatedTrades > 0 ? round((perAsset.indices.gatedWins / perAsset.indices.gatedTrades) * 100, 2) : 0,
        baselineMarginUsd: round(perAsset.indices.baselineMarginUsd, 2),
        gatedMarginUsd: round(perAsset.indices.gatedMarginUsd, 2),
        deltaMarginUsd: round(perAsset.indices.gatedMarginUsd - perAsset.indices.baselineMarginUsd, 2),
        skippedTrades: perAsset.indices.skippedTrades,
        reducedTrades: perAsset.indices.reducedTrades,
      },
      crypto: {
        baselineReturn: round(perAsset.crypto.baselineReturn),
        gatedReturn: round(perAsset.crypto.gatedReturn),
        deltaReturn: round(perAsset.crypto.gatedReturn - perAsset.crypto.baselineReturn),
        baselineTrades: perAsset.crypto.baselineTrades,
        gatedTrades: perAsset.crypto.gatedTrades,
        deltaTrades: perAsset.crypto.gatedTrades - perAsset.crypto.baselineTrades,
        baselineWinRatePct: perAsset.crypto.baselineTrades > 0 ? round((perAsset.crypto.baselineWins / perAsset.crypto.baselineTrades) * 100, 2) : 0,
        gatedWinRatePct: perAsset.crypto.gatedTrades > 0 ? round((perAsset.crypto.gatedWins / perAsset.crypto.gatedTrades) * 100, 2) : 0,
        baselineMarginUsd: round(perAsset.crypto.baselineMarginUsd, 2),
        gatedMarginUsd: round(perAsset.crypto.gatedMarginUsd, 2),
        deltaMarginUsd: round(perAsset.crypto.gatedMarginUsd - perAsset.crypto.baselineMarginUsd, 2),
        skippedTrades: perAsset.crypto.skippedTrades,
        reducedTrades: perAsset.crypto.reducedTrades,
      },
      commodities: {
        baselineReturn: round(perAsset.commodities.baselineReturn),
        gatedReturn: round(perAsset.commodities.gatedReturn),
        deltaReturn: round(perAsset.commodities.gatedReturn - perAsset.commodities.baselineReturn),
        baselineTrades: perAsset.commodities.baselineTrades,
        gatedTrades: perAsset.commodities.gatedTrades,
        deltaTrades: perAsset.commodities.gatedTrades - perAsset.commodities.baselineTrades,
        baselineWinRatePct: perAsset.commodities.baselineTrades > 0 ? round((perAsset.commodities.baselineWins / perAsset.commodities.baselineTrades) * 100, 2) : 0,
        gatedWinRatePct: perAsset.commodities.gatedTrades > 0 ? round((perAsset.commodities.gatedWins / perAsset.commodities.gatedTrades) * 100, 2) : 0,
        baselineMarginUsd: round(perAsset.commodities.baselineMarginUsd, 2),
        gatedMarginUsd: round(perAsset.commodities.gatedMarginUsd, 2),
        deltaMarginUsd: round(perAsset.commodities.gatedMarginUsd - perAsset.commodities.baselineMarginUsd, 2),
        skippedTrades: perAsset.commodities.skippedTrades,
        reducedTrades: perAsset.commodities.reducedTrades,
      },
    },
    gateDiagnostics: state.gateDiagnostics,
    weekly: state.weeklyBreakdown,
  };
}

function writeArtifacts(outPath: string, payload: Record<string, unknown>) {
  const stamp = DateTime.utc().toFormat("yyyy-LL-dd_HHmmss");
  const reportsDir = path.resolve(process.cwd(), "app", "reports", "bias-gate");
  mkdirSync(reportsDir, { recursive: true });
  const latestPath = path.join(reportsDir, "strategy-comparison-latest.json");
  const datedPath = path.join(reportsDir, `strategy-comparison-${stamp}.json`);
  const customPath = path.resolve(process.cwd(), outPath);
  writeFileSync(latestPath, JSON.stringify(payload, null, 2), "utf8");
  writeFileSync(datedPath, JSON.stringify(payload, null, 2), "utf8");
  writeFileSync(customPath, JSON.stringify(payload, null, 2), "utf8");
  console.log(`\nReport written (latest): ${latestPath}`);
  console.log(`Report written (dated): ${datedPath}`);
  console.log(`Report written (custom): ${customPath}`);
}

function withCotThresholds(base: CotGateContext, skipPercentile: number, reducePercentile: number): CotGateContext {
  return {
    byAssetClass: base.byAssetClass,
    pairMeta: base.pairMeta,
    minHistoryWeeks: base.minHistoryWeeks,
    skipPercentile,
    reducePercentile,
  };
}

async function runComparisonSet(options: {
  weeks: string[];
  gateMap: GateMap;
  cotContext: CotGateContext;
  gammaContext: GammaGateContext | null;
  sizing: SizingContext | null;
  reduceAsSkip: boolean;
}): Promise<StrategyComparison[]> {
  const universalV1 = await computeUniversalStrategy({
    weeks: options.weeks,
    models: PERFORMANCE_V1_MODELS,
    gateMap: options.gateMap,
    cotContext: options.cotContext,
    gammaContext: options.gammaContext,
    sizing: options.sizing,
    reduceAsSkip: options.reduceAsSkip,
  });
  const universalV2 = await computeUniversalStrategy({
    weeks: options.weeks,
    models: PERFORMANCE_V2_MODELS,
    gateMap: options.gateMap,
    cotContext: options.cotContext,
    gammaContext: options.gammaContext,
    sizing: options.sizing,
    reduceAsSkip: options.reduceAsSkip,
  });
  const universalV3 = await computeUniversalStrategy({
    weeks: options.weeks,
    models: PERFORMANCE_V3_MODELS,
    gateMap: options.gateMap,
    cotContext: options.cotContext,
    gammaContext: options.gammaContext,
    sizing: options.sizing,
    reduceAsSkip: options.reduceAsSkip,
  });

  const tieredBySystem = await computeTieredForWeeksAllSystems({ weeks: options.weeks });
  const tieredV1 = computeTieredStrategy({
    weeklyRows: tieredBySystem.v1,
    gateMap: options.gateMap,
    cotContext: options.cotContext,
    gammaContext: options.gammaContext,
    sizing: options.sizing,
    reduceAsSkip: options.reduceAsSkip,
  });
  const tieredV2 = computeTieredStrategy({
    weeklyRows: tieredBySystem.v2,
    gateMap: options.gateMap,
    cotContext: options.cotContext,
    gammaContext: options.gammaContext,
    sizing: options.sizing,
    reduceAsSkip: options.reduceAsSkip,
  });
  const tieredV3 = computeTieredStrategy({
    weeklyRows: tieredBySystem.v3,
    gateMap: options.gateMap,
    cotContext: options.cotContext,
    gammaContext: options.gammaContext,
    sizing: options.sizing,
    reduceAsSkip: options.reduceAsSkip,
  });

  return [
    compareStrategy("universal_v1", universalV1),
    compareStrategy("universal_v2", universalV2),
    compareStrategy("universal_v3", universalV3),
    compareStrategy("tiered_v1", tieredV1),
    compareStrategy("tiered_v2", tieredV2),
    compareStrategy("tiered_v3", tieredV3),
  ];
}

function summarizeStrategyGroup(comparisons: StrategyComparison[], group: "universal" | "tiered") {
  const rows = comparisons.filter((row) =>
    group === "universal" ? row.strategy.startsWith("universal_") : row.strategy.startsWith("tiered_"),
  );
  const count = rows.length || 1;
  const baselineTotal = rows.reduce((sum, row) => sum + row.baseline.totalReturn, 0);
  const gatedTotal = rows.reduce((sum, row) => sum + row.gated.totalReturn, 0);
  const baselineAvgDd = rows.reduce((sum, row) => sum + row.baseline.maxDrawdownPct, 0) / count;
  const gatedAvgDd = rows.reduce((sum, row) => sum + row.gated.maxDrawdownPct, 0) / count;
  const deltaReturnAvg = rows.reduce((sum, row) => sum + row.delta.totalReturnPct, 0) / count;
  const ddReductionAvg = rows.reduce((sum, row) => sum + (row.baseline.maxDrawdownPct - row.gated.maxDrawdownPct), 0) / count;
  return {
    strategyCount: rows.length,
    baselineTotalReturn: round(baselineTotal),
    gatedTotalReturn: round(gatedTotal),
    deltaTotalReturn: round(gatedTotal - baselineTotal),
    baselineAvgDrawdown: round(baselineAvgDd, 6),
    gatedAvgDrawdown: round(gatedAvgDd, 6),
    avgDrawdownReduction: round(ddReductionAvg, 6),
    avgDeltaReturn: round(deltaReturnAvg),
    score: round(deltaReturnAvg + ddReductionAvg),
  };
}

async function runThresholdSweep(options: {
  weeks: string[];
  gateMap: GateMap;
  cotContext: CotGateContext;
  gammaContext: GammaGateContext | null;
  sizing: SizingContext | null;
  skipPercentiles: number[];
  reducePercentiles: number[];
  reduceAsSkip: boolean;
}) {
  const scenarios: Array<{
    skipPercentile: number;
    reducePercentile: number;
    universal: ReturnType<typeof summarizeStrategyGroup>;
    tiered: ReturnType<typeof summarizeStrategyGroup>;
  }> = [];

  for (const skipPercentile of options.skipPercentiles) {
    for (const reducePercentile of options.reducePercentiles) {
      if (!(reducePercentile < skipPercentile)) continue;
      const cotContext = withCotThresholds(options.cotContext, skipPercentile, reducePercentile);
      const comparisons = await runComparisonSet({
        weeks: options.weeks,
        gateMap: options.gateMap,
        cotContext,
        gammaContext: options.gammaContext,
        sizing: options.sizing,
        reduceAsSkip: options.reduceAsSkip,
      });
      scenarios.push({
        skipPercentile,
        reducePercentile,
        universal: summarizeStrategyGroup(comparisons, "universal"),
        tiered: summarizeStrategyGroup(comparisons, "tiered"),
      });
    }
  }

  const universalRanked = [...scenarios].sort((a, b) => b.universal.score - a.universal.score);
  const tieredRanked = [...scenarios].sort((a, b) => b.tiered.score - a.tiered.score);
  return {
    scenarios,
    best_universal: universalRanked[0] ?? null,
    best_tiered: tieredRanked[0] ?? null,
  };
}

async function main() {
  loadEnvConfig(process.cwd());
  const config = parseArgs();
  if (config.weeks < config.weeksRequested) {
    console.log(
      `Backtest window clamped to ${RESEARCH_MAX_WEEKS} closed weeks (sentiment coverage constraint).`,
    );
  }
  const weeks = await listClosedWeeks(config.weeks);
  if (weeks.length === 0) {
    throw new Error("No closed performance weeks available.");
  }

  const gateMap = buildGateMap();
  const cotContext = await buildCotGateContext();
  const gammaContext = buildGammaGateContext(config);
  if (config.gammaMode !== "off" && !gammaContext) {
    console.log(
      `Gamma mode requested (${config.gammaMode}) but gamma inputs were missing/empty: ${config.gammaWeekOpenCsv}, ${config.gammaPairMapCsv}`,
    );
  }
  if (config.gammaMode === "only" && !gammaContext) {
    throw new Error("gamma-mode=only requires non-empty gamma CSV inputs.");
  }
  const sizing = await loadSizingContext();
  const comparisons = await runComparisonSet({
    weeks,
    gateMap,
    cotContext,
    gammaContext,
    sizing,
    reduceAsSkip: config.reduceAsSkip,
  });
  const sweep = config.sweep
    ? await runThresholdSweep({
        weeks,
        gateMap,
        cotContext,
        gammaContext,
        sizing,
        skipPercentiles: config.sweepSkipValues,
        reducePercentiles: config.sweepReduceValues,
        reduceAsSkip: config.reduceAsSkip,
      })
    : null;

  const output = {
    generated_utc: new Date().toISOString(),
    scope: {
      weeks_requested: config.weeksRequested,
      weeks_clamped_to: config.weeks,
      weeks_used: weeks.length,
      week_open_utc: weeks,
    },
    gate_sources: {
      BTC: "app/reports/bias-gate/btc-latest.json",
      ETH: "app/reports/bias-gate/eth-latest.json",
      COT_percentile: {
        enabled_asset_classes: ["fx", "indices", "commodities"],
        min_history_weeks: cotContext.minHistoryWeeks,
        reduce_percentile: cotContext.reducePercentile,
        skip_percentile: cotContext.skipPercentile,
      },
      GAMMA_week_open: gammaContext
        ? {
            mode: gammaContext.mode,
            neutral_policy: gammaContext.neutralPolicy,
            max_age_days: gammaContext.maxAgeDays,
            snapshots_csv: gammaContext.sourceFiles.snapshotsCsv,
            pair_map_csv: gammaContext.sourceFiles.pairMapCsv,
            mapped_pairs: gammaContext.pairMap.size,
            symbols_with_data: gammaContext.bySymbol.size,
          }
        : {
            mode: config.gammaMode,
            enabled: false,
            reason: "Gamma CSV inputs missing or empty.",
            snapshots_csv: config.gammaWeekOpenCsv,
            pair_map_csv: config.gammaPairMapCsv,
          },
      behavior: {
        PASS: "full_size",
        NO_DATA: "full_size",
        REDUCE: config.reduceAsSkip ? "removed_trade" : "half_size",
        SKIP: "removed_trade",
      },
    },
    sizing_context: sizing
      ? {
          source: sizing.source,
          account_id: sizing.accountId,
          account_size_usd: sizing.accountSizeUsd,
          baseline_equity: sizing.baselineEquity,
          account_scale: round(sizing.accountScale, 6),
          lot_map_rows: sizing.lotMapRows.length,
        }
      : {
          source: "none",
          note: "Margin estimates disabled (no lot_map sizing context found).",
        },
    assumptions: {
      research_window_max_weeks: RESEARCH_MAX_WEEKS,
      research_window_reason: "Sentiment dataset coverage for this phase is limited to recent 8 closed weeks.",
      concurrency: "weekly_signal_hold",
      note: "Open trades at once approximated as weekly active legs (all weekly signals considered concurrently open).",
      margin_note: "Estimated margin uses mt5 lot_map margin_required scaled by account_scale; hedging offsets are not netted.",
      cot_note: "Indices/commodities use base-only COT mode when quote market is unavailable in snapshots (e.g., USD quote).",
      gamma_note: "Gamma gate uses week-open snapshot only (no intraweek re-entry in this backtest mode).",
      reduce_mode: config.reduceAsSkip ? "REDUCE_TREATED_AS_SKIP" : "STANDARD_REDUCE_HALF_SIZE",
    },
    threshold_sweep: sweep,
    comparisons,
  };

  console.log("\n=== Strategy Gate Comparison (Closed Weeks) ===");
  console.log(`Weeks used (${weeks.length}): ${weeks.map((w) => w.slice(0, 10)).join(", ")}`);
  console.table(
    comparisons.map((row) => ({
      strategy: row.strategy,
      base_ret: row.baseline.totalReturn,
      gated_ret: row.gated.totalReturn,
      delta_ret: row.delta.totalReturnPct,
      base_dd: row.baseline.maxDrawdownPct,
      gated_dd: row.gated.maxDrawdownPct,
      delta_dd: row.delta.maxDrawdownPct,
      base_wr: row.baseline.winRatePct,
      gated_wr: row.gated.winRatePct,
      skipped: row.gateActivity.skippedTrades,
      reduced: row.gateActivity.reducedTrades,
      peak_open_base: row.capacity.peakOpenTradesBaseline,
      peak_open_gated: row.capacity.peakOpenTradesGated,
      peak_margin_base: row.capacity.peakMarginBaselineUsd,
      peak_margin_gated: row.capacity.peakMarginGatedUsd,
    })),
  );
  if (sweep) {
    console.log("\n=== Threshold Sweep (Universal/Tiered) ===");
    console.table(
      sweep.scenarios.map((row) => ({
        skip: row.skipPercentile,
        reduce: row.reducePercentile,
        uni_score: row.universal.score,
        uni_delta: row.universal.deltaTotalReturn,
        uni_dd_reduce: row.universal.avgDrawdownReduction,
        tier_score: row.tiered.score,
        tier_delta: row.tiered.deltaTotalReturn,
        tier_dd_reduce: row.tiered.avgDrawdownReduction,
      })),
    );
  }

  writeArtifacts(config.outPath, output as Record<string, unknown>);
  await getPool().end();
}

main().catch(async (error) => {
  console.error("backtest-strategy-gate-comparison failed:", error);
  await getPool().end().catch(() => undefined);
  process.exit(1);
});
